
* Dagbok
** 2018
*** Februar
**** [2018-02-25 søn]
  OL på Lillehammer, frukost og pakka ut. Reiste til Skeikampen. Måka snø, åt føremiddagsmat. Aasmund på skitur rundt Skeikampen (13 km) i kaldt snøver. Nesten ingen ute; mykje snø i skisporet. Middag: elgkjøt med rotgrønnsaker og poteter.
**** [2018-02-26 man.]
  Rensa og glidet skia mine og Bjørg Kristin sine. Etter frukost vart det tur rundt Skeikampen for Bjørg Kristin, Aud og Jan Tore (soame runde eg hadde i går). Eg gjekk over Prestkampen og Slagfjella i tillegg. Sol og kaldt (-6 til -11 grader), og lite folk over Prestkampen/Slagfjella. God glid, men til tider dårleg feste. Smurte med Grøn SWIX; det hjalp på festet.
  Eg laga middag: torsk i form med grønsaker under (fennikel, gulrot, lauk og purre kokt litt først, og cherrytomater rå) og ost over (og salt/pepper/timian). Veldig godt.  
**** [2018-02-27 tir.]
  Aasmund jobba tidleg; Bjørg Kristin jobba fram til 15.30 (Skype). Skitrekket stengt på grunn av vind (og sterk kulde). Aasmund over Kyrakampen og Austlid, 17 km. Aasmund besøkte Arve og Sunniva, og henta Andreas i Lillehammer. Lasagne til middag.
**** [2018-02-28 ons.]
  Pannebrød til frukost. Aud og Bjørg Kristin skitur Frøysesetra-Austlid, Andreas og Aasmund Frøysesetra-Kyrakampen-Austlid, 17 km. Fish'n crisp med erter til middag, vafler til kveldsmat. Aasmund reinskreiv Landås menighets høyringsutkast til virksomhetsgjennomgangen.
*** Mars
**** [2018-03-01 tor.]
  Pannebrød til frukost; i dag stekt i godt smør, men det gjorde at dei vart litt "grå" (og nokre vart svidd). Soft Soya/olje er kanskje betre?
  Aasmund og Andreas i bakken om føremiddagen (eg hadde avklart med Håvard at det ikkje skjedde noko med omlegging av eksport før om ettermiddagen), og Aasmund og Jan Tore måkte snø av taket etter lunsj (omlegginga art utsatt til fredag ...). Middag: kyllingform etter Instagram, men med litt endringar:
  Lauk, paprika (raud/grøn/gul) og kyllingfiletar vendt i krydder, ris og rikeleg hønsebuljong i form, og kyllingar/grønsaker over, dekt med folie og i ovn (190-200 grader) i 40 minutt. Flytt øverst i omnen med grill 5 minutt ekstra.
  Det kunne vore litt mindre væske, men kraftigare smak i væska. Krydderblandinga (paprika, salt, pepper, timian, lammekrydder) kunne vore meir "taco", dvs. kummin og kvitlauk. Men veldig godt.
  Aasmund gjekk rundt Skeikampen frå 22.00 til 24.00, i -20 grader, fullmåne og stjerneklart. Fantastisk flott.
**** [2018-03-02 fre.]
  Aasmund leste litt e-postar før frukost, og meldte avbod til Skype-møtet (sjølv om David hadde utvida det for at vi skulle "setle" tysdag 20. mars) Fellestur "Kjølen hematt" til Fjerdum. Overskya, men ganske kaldt (så ingen pauser). Ca. 25 km. Pasta carbonara (Andreas) til middag. Alle heilt utslått etterpå; kinasjakk om kvelden.
**** [2018-03-03 lør.]
  Aasmund og Andreas i bakken det meste av føremiddagen; Bjørg Kristin gjekk langs Peer Gynt-vegen. Aud henta Irene og gutane på Lillehammer. Aasmund bakte "Skillingsbollekake" til kaffe (1/2 nok til åtte personar ...) og Aud lagde pizza til kvelds. Aasmund pakka skiutstyret i bilen. 
**** [2018-03-04 søn.]
   Aasmund leste e-postar, steikte pannebrød og trolldeig for Trym og Kristoffer. Vi køyrte før 10.00; roleg og fin køyring, men litt glatt over Vingrom-Leira (begge overgangane). Kø frå Trengereid til Arna; 30 minutt forsinka. Ikkje så verst kaldt i huset.
**** [2018-03-05 man.]
  Oppdatering på e-post etter vinterferien. Ein del superbrukarting, og litt om opplæring (20. mars og planar for april/mai). Jegergryte med ein pakke biffstrimler, ein halv lauk og to gulrøtter, og kokte poteter. Fokusgruppe om Smappee på UiB om kvelden. Bjørg Kristin besøkte Inta og Helge og snakka om Knut som døydde 22. februar. Gravferda er no på torsdag; Helge skal ha den.
**** [2018-03-06 tir.]
  Bjørg Kristin reiste til Oslo om føremiddagen (styremøte i VID), vidare til styremøte på HVL i Førde onsdag. Big Blue Button-kurs med Johan Bruland om føremiddagen. Mykje tid (25 av 60 minutt) går vekk til at folk ikkje har det tekniske utstyret på plass før kurset begynner :-( Gjorde ferdig alt teoristoff til førelesingane neste veke. Lang samtale med Håvard H om fagforening og Connie. Måkte snø frå altanen (ca. halvparten; resten er mykje is). Middag: ein lauk, ei gulrot, litt kvitvinseddik og smakssatt olje (reklamepose) og 1/2 boks "Norrlandspølse" (svensk lungemos). Korøving, og prata litt med far om kvelden. Han ønsker seg inspirasjon til å lage mat av alle grønnsakene han har i frysen.  
**** [2018-03-07 ons.]
  Lang dag på jobb; henta dress på Tiger og gjekk på kino (Black panther). Seint heim; restane av lungemosen frå dagen før til middag.
**** [2018-03-08 tor.]
  Gravferd for Knut Torsheim Gundersen frå Bremnes kyrkje.
  Starta med litt jobb (og frivillighet) heime; pakka bilen og køyrte til Bømlo med Lene Frøyen som passasjer. Veldig hyggeleg; i hadde mykje å prate om. Frå "Landås" kom vi to, May Elisabeth/Odd Helge, og Liv Karin/Ingrid. Veldig fin gravferd, med svært mange gode ord om Knut. Minnesamvær på Ungdomsheimen (KFUK/M) på Svortland; ferdig 17.45. Heim til Bergen; henta PC på jobb, og køyrte til Sogndal. 30 minutt venting på kolonne i Gudvangatunnellen; framme 01.00 ...
**** [2018-03-09 fre.]
  Enkel frukost med Bjørg Kristin, og jobb i Høgskulebygget fram til 15.45. Besøkte mor, som var i godt humør. Vi snakka mest om barnebarna i Arnafjord. Handla litt middag, henta Bjørg Kristin og køyrte til Fjærland. Far hadde insistert på å "bli inspirert til å lage mat med grønnsakene jeg har i fryseren", så han måtte lage lapskaus på dei og innkjøpt kålrot/middagspølse. 
**** [2018-03-10 lør.]
  Roleg dag i huset. Nils og Una med ungane kom om ettermiddag; Nils skulle klippe sau laurdag og sundag. 50 km på fjernsyn, og pai til middag. Haldor har lært enormt mange ord sidan i februar, og han "smaker" heile tida på nye ord. Aasmund hengte opp ny taklampe i stova.
**** [2018-03-11 søn.]
  Nok ein roleg dag. Nils klipte sau frå tidleg. Aasmund og Una gjekk lang tur med Haldor (til fots). Restemiddag (fårikål og svineribbe frå fryseboksen). Aasmund limte to av settborda. Heim til Bergen ca. 20.00.
**** [2018-03-29 tor.]
  Skjærtorsdag. Pakka i bilen, og reiste frå by'n 10.30. Fin køyring til Tyin; kort stopp på Voss for meir kaffe. Helge og Inta sov litt i baksetet (dei hadde vore oppe til 03.00 av di Kristin hadde fest). Pakka ut, åt litt mat, og gjekk på skitur opp mot Tenlekrysset. Eg gjekk litt lengre mot Sulebu, og snudde då det vart skugge. Kaldt, ca. -7 grader, og hard, fin snø. Vi oppdaga lekkasje i boden, og prøvde å avverge den mest mogleg. Litt vellukka, men det må ein større reparasjon til når all snøen er vekk. Middag og kveldskos; H & I sovna 22.00.
**** [2018-03-30 fre.]
Langfredag. I følge termometeret -17 grader om morgonen. Lang frukost; venta på at Inta skulle bli i form til å gå ut. Eg og Bjørg Kristin gjekk først. Til Tendlekrysset, så Tendlehytta med rast, og vidare mot Vardhovdtinden (ikkje heilt til toppen), og så i retning Sulebu. Ved Vardhøflænane tok vi rett ned til Tendlekrysset og til hytta. 16 km i gnistrande flott sol, og relativt godt føre (grønt). Helge og Inta hadde då vore på Sulebu i mellomtida. Middag: chevre med glaserte valnøtter, rødbeter og salat til forrett; ovnsbakt laks til hovudrett og Giant cinnamon cake til dessert. Måneskinnstur med spark.
**** [2018-03-31 lør.]
Alle på tur til Tendlehytta. Ingen ting spesielt. Lammesteik og krumkaker med moltekrem til middag.
*** April
**** [2018-04-01 søn.]
  Påskedag. Aasmund gjekk på ski til Tomaskyrkja, og vart med dei andre heim. Alle gjekk til Sulebu etterpå. Merkbart mindre folk i løypene; heimfarten var starta. Finnbiff og eplepai til middag. "Heimebane" og påskekrim på TV. Helge gjekk ned med feber om kvelden.
*** September
**** [2018-09-21 fr.]
Vanleg dag på jobb; fant ut av import av karakterar til Canvas. Pizza med grønkål og rødbeter til middag.
**** [2018-09-22 la.]
Aasmund laga eplechutney og sylta ingefær, køyrte kajakkane til Sotra, og styremøte i velforeininga. Bjørg Kristin rydda på loftet. Hjå Ottar og Tove til middag og kvelds.
**** [2018-09-23 søn.]
Familiegudsteneste med mykje folk og dåp. Svært ustabilt ver, rydda inne. Andreas på middag; bayonneskinke med grønnsaker. Ringte med far; han hadde hatt besøk av Nils med familie og var i godt humør.
**** [2018-09-24 man.]
Bjørg Kristin reiste med båt til Sogndal. Min "første" undervisingstime, redaksjonsmøte i Tangenten og bibelguppe. 
**** [2018-09-25 ty.]
Vanleg dag på jobb, korøving (få frammøtte)
**** [2018-09-26 on.]
Pent ver om ettermiddagen; sykla til Svartediket, gjekk opp Isdalen, løp til Borgarskardet og Tarlebøvatnet. Kneet gjorde vondt då, for det var ein litt for lang tur. Men det vart litt betre etter at eg småløp ned til sykkelen.
**** [2018-09-27 to.]
Undervising med den andre gruppa studentar. Dei er mykje meir vakne og konstruktivt kritiske til undervisinga enn den andre gruppa. Jobba lenge; henta Bjørg Kristin på Flesland, og laga gulrotsuppe til middag.
**** [2018-09-28 fr.] 
Pent ver om ettermiddagen; sykla over Rundemanen. Middag hjå Eyvind Rødal om kvelden med Anne Isine og Vidar (og Marit). Sat lenge; heime 01.00
**** [2018-09-29 la.]
Lang frukost. Kort og våt bytur. Helge og Inta på kyllingsuppe som kveldsmat; dei hadde vore på Bømlo på dagsbesøk.
**** [2018-09-30 sø.]
Gudsteneste med kristin Lødøen Hope, lang kyrkjekaffe. Roleg heime, og tidleg middag. Bjørg Kristin reiste med båt til Sogndal (tilbake tysdag med fly). Snakka med far; han hadde vore på busstur med sogelaget til Luster. Det likte han.
*** Oktober
**** [2018-10-01 må.]
Slo av det meste av telefon og førebudde undervising. Brukte ein (dobbelt)time med god tid til å gå gjennom det som er temaet heile denne veka. Lurer på om eg berre skal avlyse førelesinga i morgon. Relativt pent ver etter jobb; sykla til Svartediket, gjekk opp Isdalen, og løp ned Borgaskardet og Hardbakkedalen. Veldig sleipt, så det gjekk litt sakte. Arbeida med nye Begynneropplæringen om kvelden, og satte opp Emacs som Python IDE.
**** [2018-10-02 ty.]
Ei ikkje heilt vellukka førelesing om kombinert usikkerhet. Korøving, med mange (heldigvis). Bjørg Kristin kom seint, med fly frå Sogndal via Oslo. 
**** [2018-10-03 on.]
Helga tilbake i jobb, møte med henne og Lars Arne om framdrifta i ELE103. Svartediket - Isdalen - Borgaskardet - Hardbakkedalen etter jobb. Like sleipt som måndag, men kjente terrenget betre, så det gjekk litt fortare. Bjørg Kristin på styremøte i Ulriken KM.
**** [2018-10-04 to.]
Undervising i den "vanlege" klassen i ELE103. Ingen ting spesielt.
**** [2018-10-05 fr.]
Veldig god førelesing om kombinert usikkerhet; eg trur at eg legg denne ut til den andre gruppa og seier at "ja, det er ikkje den førelesinga de fekk, men denne er betre". Johannes kom til Kolstien etter jobb og laga knekkebrød; Vigdis og Andreas kom litt seinare og åt middag (pai). Veldig kjekt. Johannes og Vigdis forkjølte.
**** [2018-10-06 la.]
Tømte kompostbingen; veldig fin kompost i den nederste halvparten. Bytur med Johannes etterpå (han skal få islender), med napoleonskake på Lie Nilsen. 
**** [2018-10-07 sø.]
Fly til London. Rakk Evensong i St Martin-in-the-Fields. Spasertur gjennom Whitehall og langs Themsen. Fant restauranten "Belgo Holborn".
**** [2018-10-08 må.]
"Norsk dag" på Barbican. Veldig nyttig. "Bytur" med HVL-gjengen (innom Belgo), og indisk middag. Pubtur etterpå.
**** [2018-10-09 ty.]
Hemorroidane slo ut i full blomst. Sjølve CanvasCon i Barbican. Stort sett nyttig, men ingen ting spesielt. Tok undergrunnen til Notting Hill Gate, åt på ein pub, og gjekk ein lang tur gjennom Notting Hill og Kensington etterpå. Kino på Odeon: Johnny English 3
**** [2018-10-10 on.]
British Museum (klokke- og myntsamlinga), shopping (souvenirar på London Transpor Museum og sko på Vivobarefoot), reiste ut på Heathrow. Litt forsinkelsar jamt over, men i Bergen ca. 2100. Hemorroidane ille.
**** [2018-10-11 to.]
Kort undervisingsøkt om kombinert usikkerhet og usikkerhetsbudsjett. Bjørg Kristin kom heim frå Haugesund.
**** [2018-10-12 fr.]
Roleg dag på jobb. Bjørg Kristin arbeidde heime.
**** [2018-10-13 la.]
Grått og regn. Sov lenge, litt shoppping på Lagunen. Strømmet Erin Brockovich på Prime TV.
**** [2018-10-14 sø.]
Grått og regn. Eg var medliturg saman med Gina Thu (teologistudent som har hatt observasjonspraksis hjå Åse Kristin).
**** [2018-10-15 må.]
Skifta dekk på bilen og bytta batteri i nøklane (Møller Kokstad og Møller Nesttun). Køyrte bilen på jobb så Bjørg Kristin kunne ta den til Flesland. Planla "Canvas-kafe" med grupper og innleveringar. Gjekk raskt opp til Ulriken og småløp over Nubben til Nattlandsfjellet og heim. Merka tydeleg at eg får vondt i knea av å løpe på flat veg. Eller greitt.
Arbeida med Fosnot (lang prat med Marit), og diskuterte trusopplæring med Hilde Trætteberg Serkland. 
**** [2018-10-16 ty.]
Korøving
**** [2018-10-17 on.]
Canvas-kafe i Fyrrommet; veldig nyttig for alle. Eg lærte ein del om kvar frustrasjonen ligg.
**** [2018-10-18 to.]
Bjørg Kristin reiste til Sogndal med båten. Soknerådsmøte.
**** [2018-10-19 fr.]
Reiste tidleg (05.00) til Sogndal. Stille og roleg køyring. Full arbeidsdag i Sogndal; mellom anna aktiv i Canvas-kafeen om innleveringar. Til Fjærland etterpå. Ingen ting spesielt.
**** [2018-10-20 la.]
Regn og regn i Fjærland. Skulle frese åkeren, men Hondaen ville ikkje starte (Nils fant ut at det var dårleg plugg), så eg saga og bar ved i staden for. Nils med Haldor og Ivar kom inn om ettermiddagen. Veldig kjekt å vere saman med gutane.
**** [2018-10-21 sø.]
Regn og regn. Nils og gutane reiste om ettermiddagen. Vi andre på fårikål og feriereferat hjå Laura og Nils.
**** [2018-10-22 må.]
Regn. Køyrte til Førde og arbeidde derifrå til 1600; så til Bergen. Ingen køar, og fin køyring.
**** [2018-10-23 ty.]
Vanleg dag på jobb. Korøving.
**** [2018-10-24 on.]
Kurs i innleveringar for FØS. Tre frammøtte, men veldig nyttig for dei. Sykla til Eidsvåg etter jobb; orienteringsmøte om virksomhetsgjennomgangen til BKF. Sykla heim att; det var litt meir regn enn eg hadde lyst til. Vekas trim.
**** [2018-10-25 to.]
Køyrte på Sotra for å stenge vatn og få installert ny straummålar. Vanleg dag på jobb. Mykje Tangenten etter jobb. Sendte også Fosnot til Marit/Eli for sluttføring.
**** [2018-10-26 fr.]
Halv dag på jobb, så møte med Rune Herheim om Tangenten (vi er veldig nøgde), og litt meir på jobb før heim og helg.
**** [2018-10-27 la.]
Sein frukost. Arbeidde litt med Tangenten (ferdig kommentarar frå Rune og sendte til redaksjonen). Fulgte masse med på KrF sine årsmøøter i fem fylker. Bursdag hjå Inta om kvelden; dei fire søstrene med menn.
**** [2018-10-28 sø.]
Fly til Oslo om morgonen, sjekka inn på hotellet (Opera). Gjekk strandpromenaden til Rådhusplassen. Besøkte Nobel-museet. Gjekk opp til slottet og besøkte stallene. Litt meir byvandring og middagskvil på hotellet. "Book of Mormon" på Det norske teateret. Veldig bra. Middag på "Dinner", asiatisk Michelin-restaurant. Veldig god mat.
**** [2018-10-29 må.]
Shopping; ny vinterfrakk (halvlang) til meg. Eg tok fly til Bergen om kvelden; Bjørg Kristin vart att for å vere på møte i VID tysdag.
**** [2018-10-30 ty.]
Vanleg dag på jobb. Pent ver, så eg sykla over Rundemanen heim frå jobb. Tangenten, Fosnot og korøving om kvelden.
**** [2018-10-31 on.]
Vårt første webinar om Canvas for heile HVL. Ikkje mange deltakarar, men artig å ha prøvd det. Eg opplevde at samspelet mellom Jan Erik og meg fungerte bra. Førebuing til undervising og bibelgruppe om kvelden.
*** November
**** [2018-11-01 to.]
Veldig vellukka undervising om kontrolldiagram (følte eg i alle fall ...). Ekstremt labert oppmøte på rekneøvingar etterpå, men god tid til å førebu meg ferdig til fredag, hjelpe han eine (!) som møtte, og rette ferdig innleveringane for dei som leverte i grupper. 
**** [2018-11-02 fr.]
Også god undervising om kontrolldiagram. Ingen ting spesielt etterpå på jobb. Køyrte til Fjærland med Johannes og Vigdis etterpå. God køyring, og hyggeleg med selskap i bilen. Far tok godt i mot Vigdis.
**** [2018-11-03 la.]
Starta med vanleg sein frukost, og gjekk ut for å jobbe med gjerde (vestenden; fram mot dalen). Vigdis kom ut etter kvart. Johannes og Vigdis gjekk tur etterpå. Nils & Laura kom opp med mat, og Nils og eg laga middag. Veldig hyggeleg kveld.
**** [2018-11-04 sø.]
Ingen ting spesielt, grått og regn. Johannes og Vigdis på tur nede i bygda om føremiddagen. Heim til Bergen om ettermiddagen.
**** [2018-11-05 må.]
Pent vær, så eg gjekk opp Ulrikseggen og ned Trolldalen/Isdalen. Hadde gløymt at klokka var skrudd tilbake, så det vart mykje mørkare enn eg hadde trudd. Men eg kunne stien, så det gjekk bra. Andreas heime på middag, og så Tensing i Ytrebygda etterpå. Veldig bra.
**** [2018-11-06 ty.]
Ingen ting spesielt på jobb. Korøving.
**** [2018-11-07 on.]
Bjørg Kristin reiste til Sandefjord om morgonen, heim torsdag. AU i soknerådet om ettermiddagen, "Bohemian Raphsody" om kvelden. Veldig bra film, Rami Malek svært imponerande i rolla som Freddie Mercury.
**** [2018-11-08 to.]
Litt vanskeleg time om regresjon, men det gjekk rimeleg bra. Svært mange på rekneøvingane. Sykla Løvstien frå Melkeplassen. Henta Bjørg Kristin på Flesland om kvelden.
**** [2018-11-09 fr.]
Rimeleg grei time om regresjon; kom ikkje så langt som planlagt på grunn av mange (gode) spørsmål. Hektisk resten av dagen med Canvas hjelpetelefon og rekneøving. Til kontroll for tannimplantatet, alt er veldig bra. Biff til kveldsmat.
**** [2018-11-10 la.]
Lang frukost. Gjekk opp "Oppstemten" til Ulriken. Traff mellom anna Lars og Eirin to ganger (på veg opp og ned). Wok til middag. Oppvaskemaskina rauk om kvelden.
**** [2018-11-11 sø.]
Farsdag, fekk "Ssterklokkene" av Lars Mytting og det siste bandet av Michelet sine bøker om krigsseilarane. Bjørg Kristin medliturg og eg i kyrkjekoret. Begge delar gjekk bra. Lang kyrkjekaffe etterpå; det er tydeleg at svært mange set pris på å sitje og prate når veret ikkje er veldig bra til å gå ut. Andreas til middag (hjortegryte) og "Søndagskveld på Landås".
**** [2018-11-12 må.]
Laga skisse til eksamensoppgåver på jobb. Mobilen rauk på jobb; har bestilt ny (OnePlus 6, Telia) og skal hente i morgon. Opp Trolldalen og ned Hardbakke; veldig bra med den "gamle" hodelykta. Litt regn.
**** [2018-11-13 ty.]
Korøving om kvelden.
**** [2018-11-14 on.]
Bibelgruppe hjå Aslaug om kvelden.
**** [2018-11-15 to.]
Nest siste økt med undervising. Ikkje så veldig nøgd, men det er litt rotete stoff (kalibrering). Sjå forøvrig diskusjoenn med Kjell Eivind. Gjorde eit poeng av kilogram-prototypen i Paris, og at den no er på veg ut. Soknerådsmøte. Veldig god stemning; det er tydeleg at Åse Kristin er såpass varm i trøya og trygg på soknerådet at vi kan ha gode diskusjonar som gjer at ho verkeleg lytter til oss.
**** [2018-11-16 fr.]
Dårleg undervising; gjorde eit poeng av at det å arbeide med konkrete problem kan vere ganske innfløkt også for oss lærarar. Sykla til Melkeplassen, og småløp opp til Løvstakken med ny lykt. Den fungerte heilt fint. Flott panoramabilete av Fyllingsdalen frå toppen. Fekk følge av ein annan nedover, han var meir kjent. Hyggeleg å småprate, og kjekt å sjå at eg kunne løpe like fort og lett som han på ukjend sti.
Henta Bjørg Kristin på Flesland, ferdigpizza til kvelds.
**** [2018-11-17 la.] 
Inspirasjonssamling for sokneråd i Knarvik 1000-1700. Veldig god samling, med både gode føredrag og diskusjon rundt borda. Representanten frå Åsane er kamerat av Mons, så det vart litt intern prating der. Landås menighet vart fokusert litt mykje: eg holdt eit lite innlegg der eg ønska at vi skulle bli endå betre på å integrere kyrkja i lokalsamfunnet, og journalist Frøy Gulbrandsen i BT sa at på Landås var kyrkja verkeleg lett å få auge på, at den var nettopp ein synleg del av lokalmiljøet. (Ho kom lenge etter at eg hadde holdt innlegget, så der traff eg godt ...)
**** [2018-11-18 sø.]
Familiegudsteneste med mykje livlige ungar, og lang god kyrkjekaffe etterpå. Roleg arbeids- og lesedag inne (sjølv om det var relativt fint ver), og Laura på middag om kvelden. Ho kom frå Oslo og skulle vere to dagar i by'n.
**** [2018-11-19 må.]
Bjørg Kristin med fly til Sogndal etter jobb. Løp Isdalen-Hardbakke-Tarlebø etter jobb; flotte bilete av lyset. Kaldt, og litt isete. Prostisamling om kvelden; mange er for betre samarbeid, og eg ser kimen til at storleiken på dette forumet (9 sokn) er akkurat passe stort til diskusjonane (og så kan Fellesrådet ta seg av vedtaka ...)
**** [2018-11-20 ty.]
Arbeida heime om føremiddagen; oppvaskmaskina fekk service men vart kvitta ut. Tok litt ekstra for Helga; ho er sjukmeldt ut året. Korøving, Bjørg Kristin heim frå Førde.
**** [2018-11-21 on.]
Bjørg Kristin med tidleg fly til Oslo. Gjorde ferdig eksamenssettet til ELE103. Lang prat med Kjell Eivind om det "nye" ELE103; vi er mykje meir einige enn det Helga og eg var. Det nye kjem til å likne meir på BYG102, med statistikken som litt ei eigen del, og litt fletta saman med måleteknikk. Viktig at vi ikkje tråkker i kvarandres bed, men at vi snakker saman så mykje som råd, slik at vi formidler det same til studentane.
Kjøpte ny oppvaskmaskin om ettermiddagen. Andreas kom heim og hjalp å bære inn ny og ut gamal. Ringte Una og gratulerte henne og Ivar med dagane.
**** [2018-11-22 to.]
Siste ordinære undervisingstime; eg parafraserte litt over "signal vs støy" og gjorde litt andre ting enn Helga i kapittel 9. Kort spørjetime etterpå. To rekneøvingar. Den første var berre ein svak student, så eg gjekk heller opp til Lars Arne og gjekk gjennom høyring til nytt ELE103. Den andre rekneøvinga var veldig god, med dei fire vanlege studentane. Lang prat med Håvard Helstrup om ulike frustrasjonar ved jobb og privatliv etterpå. Køyrte gamal oppvaskmaskin til gjenbruk, og henta Bjørg Kristin på Flesland. 

**** [2018-11-23 fr.]
Bjørg Kristin til Solstrand, og så til Fjærland om kvelden. Framme 21.30. Kaldt, og pent. Kyllinggryte.

**** [2018-11-24 la.]
Gjorde svært lite; Bjørg Kristin og far rydda litt på loftet (sengetøy), og ein liten tur på butikken.

**** [2018-11-25 sø.]
Rydda litt meir å loftet, og la planer for at far kan pusse opp det austre gjesterommet. Lunsj/middag hjå Laura og Nils. Køyrte til Sogndal om kvelden og fyrte opp i ovnen. Bjørg Kristin henta Svanaug på båten, og enkel kveldsmat etterpå.

**** [2018-11-26 må.]
Jobba i Sogndal; tenkte høgt rundt samling på Voss (?) for superbrukarar i Canvas. Køyrte til Bergen om kvelden. 

**** [2018-11-27 ty.]
Diverse på jobb; lang prat med Johan om faren som døydde forrige torsdag. Sykla til Nesttun og henta nye viskarar til bilen. Korøving. Kokte ein porsjon søtpotetsuppe.
**** [2018-11-28 on.]
Diverse på jobb. Opp Hardbakkedalen og over til Tarlebø om ettermiddagen. Hadde ikkje dei gode skoene, så eg tok ingen sjanser på ukjend sti. Bjørg Kristin i Haugesund på styremøte til torsdag.
**** [2018-11-29 to.]
Starta med langt budsjettmøte i kyrkja. Karin er veldig ryddig, og god å jobbe saman med. Diverse på jobb. Laga salat og tok med til bursdag/Thanksgiving hjå Asta. Kristin Marcela var kommet heim frå Colombia. Veldig kjekt. Bjørg Kristin kom direkte frå Haugesund.
**** [2018-11-30 fr.]
Bjørg Kristin på middag med kinesere om kvelden; eg gjorde ingen ting spesielt.
**** [2018-12-01 la.]
Svarte på anbod frå murar og bestilte oppstart av arbeidet så fort som råd. Baking til jul med bibelgruppa; veldig hyggeleg og effektivt. Middag (nesten bursdag) hjå Jan og Mette om kvelden, berre oss fire. Mykje om Mette, men stort sett kjekt.
**** [2018-12-02 sø.]
Gudsteneste med dåp, og juleverkstad i Lystgården etterpå. Lærte å lage stjerne med 30 (!) spisser, men ga den til Åse Kristin. Bjørg Kristin laga krans til ytterdøra. Julekonsert i Domkirken om kvelden.
**** [2018-12-03 må.]
Roleg på jobb, regn og grått ute.
** 2019
*** Januar
**** <2019-01-01 ty.>
Sto seint opp, gjorde lite. Flytta ting for Johannes, Vigdis og Andreas om kvelden.
**** <2019-01-02 on.>
Aasmund på jobb frå lunsj; Bjørg Kristin litt jobb heime.
**** <2019-01-03 to.>
Aasmund seminar om strategi ved FIN frå lunsj. Bjørg Kristin på fylkesmannens årskonferanse. Tante Inger døydde (etter lungebetennelse i romjula).
**** <2019-01-04 fr.>
Aasmund seminar om strategi til lunsj, diverse Canvas etterpå. Anna Lan Lysebo sin 18-årsdag om kvelden, masse folk og god stemning. Heime ca. 0100. Lite/ingen snakk om Svala sine plager, men det var også viktig for Asta at livet "går som normalt".
**** <2019-01-05 la.>
Seint opp; grått ute. Aasmund jobba litt Canvas, Bjørg Kristin såg sport. Andreas innom for å hente dress og litt til. Han har fått tilbod om vakter på nyopna restaurant på Danmarksplass i januar; det passer bra når han har lite å gjere på i Kafe Norge.
**** <2019-01-06 sø.>
Familiegudsteneste og juletrefest i Landås kirke. 170 ++ til stades, stor stemning. Åse Kristin, Hilde og Melanie hadde ei veldig fin "preike" som var ei forteljing med musikkinnslag. Bjørg Kristin, Aasmund og May Elisabeth rydda på kjøkenet. Roleg dag heime etterpå. 
**** <2019-01-07 må.>
**** <2019-01-08 ty.>
**** <2019-01-09 on.>
**** <2019-01-10 to.>
Bjørg Kristin henta Aud på Flesland, enkel kveldsmat.
**** <2019-01-11 fr.>
Gravferd for tante Inger frå Sandviken kyrkje til Eidsvåg kirkegård. Minnesamvær i Sandviken menighetshus etterpå. Veldig fint. Aasmund og Bjørg Kristin på nyttårsfest hjå Berit Rogne etterpå. Kjekt, men det er godt vi ikkje er i selskap som ser så djupt i glaset kvar helg ...
**** <2019-01-12 la.> 
Roleg dag heime. Aud, Aasmund og Bjørg Kristin rydda til og laga mat til Bjørg Kristin sin bursdag. 18 til middag, og Laura/Nils til kaffe i tillegg. Stor stemning som vanleg.
**** <2019-01-13 sø.>
Først til gudsteneste; Aud hadde veldig stor sans for Åse Kristin som prest. Aasmund med Laura/Nils til tante Sidsel på "formiddagsvisitt" saman med Anne og William. Full utveksling av stoda for dei respektive familiemedlemmene. Andreas til middag her etterpå; pannekaker etter hans ønske. Rydda ut jula.
**** <2019-01-14 må.>
Bjørg Kristin til Sogndal med fly. Aasmund såg resten av Game of Thrones sesong 6.
**** <2019-01-15 ty.>
Bjørg Kristin frå Sogndal med fly om kvelden. Aasmund satte Christophs artikkel til Tangenten, og korøving etterpå. Ein "hard kjerne" etter prosjektkoret i fjor haust, men trass alt 15 til saman.
**** <2019-01-16 on.>
Bjørg Kristin til Flesland på leiarmøte. Johannes ringte for å fortelje om boligjakten. Det ser ut som dei kan få napp til ein overkommeleg pris på ein leilighet i Kristofer Jansons vei (stjerneblokk).


* Mat
** 2018
*** August
| Dag | Title                   | Description                                   |
|  24 | Karbonader              |                                               |
|  25 | Laksefilet              | Rotgrønnsaker og Øygardspoteter i ovn         |
|  26 | Kyllinggryte            |                                               |
|  27 | Chili con carne med lam |                                               |
|  28 | Innbakt fisk            | Med pommes frittes                            |
|  29 | Fiskesuppe              | Med suppeboller og lyse rundstykker           |
|  30 | Vegetarpasta            | Kantina på Sammen.                            |
|  31 | Lammekoteletter         | Potetstappe med kvitlauk, rotgrønnsaker i ovn |

*** September
| Dag | Rett                              | Kommentar                                 |
|-----+-----------------------------------+-------------------------------------------|
|  01 | Salat med skinke og ostefat       |                                           |
|  02 | Fårikål                           |                                           |
|  03 | Potetgraut                        |                                           |
|  04 | Rester: potetgraut med honning    |                                           |
|  06 | Rester: fårikål                   |                                           |
|  07 | Moussaka                          | Med lam og aubergine                      |
|  09 | Pulled pork                       | Med rotgrønnsaker                         |
|  12 | Rester Moussaka                   |                                           |
|  13 | Thai-suppe m/kikerter             | Ferdigkjøpt frå Rema                      |
|  14 | Wok                               | Fredagskveld i Fjærland                   |
|  15 | Lasagne                           | Heimelaga, i Fjærland med Endre på besøk  |
|  16 | Fårikål                           | I Fjærland                                |
|  17 | Rester Lasagne                    |                                           |
|  18 | Rester fårikål                    |                                           |
|  19 |                                   |                                           |
|  20 |                                   |                                           |
|  21 | Pizza m/grønkål, brie og rødbeter | Fredag kveld, inspirert av [[Pizza med brie][Pizza med brie]] |
|  22 |                                   |                                           |
|  23 |                                   |                                           |
|  24 | Thai-suppe m/kikerter             | Kveldsmat for bibelgruppa                 |
|  25 | Stekt lauk, blomkål, poteter      |                                           |
|  26 | Stekt lauk, blomkål, poteter      | Reprise frå tysdagen :-)                  |
|  27 | [[https://trinesmatblogg.no/recipe/spicy-gulrotsuppe-med-bacon/][Gulrotsuppe m/chili]]               | Bjørg Kristin med fly frå Sogndal         |
|  28 | Lam ytre- og indrefilet           | Middag hjå Eyvind Rødal                   |
|  29 | [[https://trinesmatblogg.no/recipe/kyllingsuppe-med-karri-tomat-og-eple/][Kyllingsuppe]]                      | Helge og Inta på besøk                    |
|  30 | [[Torskefilet med grønkål]]           |                                           |

*** Oktober
| Dag | Rett                | Kommentar                                                                                                                                                                              |
|  01 | Rester Pizza        | Med litt lauk og grønkål blanka i panne og trukket med Worcestershire-saus                                                                                                             |
|  02 | Vegetar             | Steikt lauk og ester av blomkål                                                                                                                                                        |
|  03 | Seikarbonader       | Med heimelaga "Bokhvete-ciabatta"                                                                                                                                                      |
|  04 | Plukkfisk           | Med sellerirot og sjalottlauk                                                                                                                                                          |
|  05 | Pai                 | Ein vegetar (blåmuggost og grønkål) og ein med bacon                                                                                                                                   |
|  06 | Wok                 | Med scampi og                                                                                                                                                                          |
|  07 | Liege meatballs     | "Belgo Holborne" - belgisk restaurant i London. Kjøttboller (kraftige, i bacon-saus) med potetstappe (halvparten purre) og sylta rødbeter. Kraftig ostekake med Duchesse de Bourgogne. |
|  08 | Indisk              | Indisk restaurant i Neal Street, London                                                                                                                                                |
|  09 | Fish and chips      | Med "mushy peas", på puben Old Swan (Notting Hill Gate)                                                                                                                                |
|  10 | Burger              | På Heathrow                                                                                                                                                                            |
|  11 | Blodpølse           |                                                                                                                                                                                        |
|  12 | Taco i form         |                                                                                                                                                                                        |
|  13 | Butter chicken      | Alt for sterk indisk saus                                                                                                                                                              |
|  14 | Fårikål             | Rester frå Fjærland (i september)                                                                                                                                                      |
|  15 |                     |                                                                                                                                                                                        |
|  16 |                     |                                                                                                                                                                                        |
|  17 |                     |                                                                                                                                                                                        |
|  18 | Rester              |                                                                                                                                                                                        |
|  19 |                     |                                                                                                                                                                                        |
|  20 | Pizza               | I Fjærland med Nils, Haldor og Ivar                                                                                                                                                    |
|  21 | Fårikål             | Hjå Laura og Nils                                                                                                                                                                      |
|  22 | Rester              | Pizza frå Fjærland                                                                                                                                                                     |
|  23 | Søtpotetsuppe       |                                                                                                                                                                                        |
|  24 | Rester              | Pizza frå Fjærland                                                                                                                                                                     |
|  25 | Plukkfisk           |                                                                                                                                                                                        |
|  26 | Pasta med svinekjøt | Saus av blåmuggost med bønner og purre.                                                                                                                                                |
|  27 | Lammegryte          | Bursdag hjå Inta                                                                                                                                                                       |
|  28 | Asiatisk            | [[https://dinner.no/no/][Dinner]] i Stortingsgata, Oslo                                                                                                                                                           |
|  29 | Burger              | Oplandske på Oslo S                                                                                                                                                                    |
|  30 | Pytt i panne        |                                                                                                                                                                                        |
|  31 |                     |                                                                                                                                                                                        |

*** November
| Dag | Rett                            | Kommentar                                             |
|-----+---------------------------------+-------------------------------------------------------|
|   1 | Sellerirotsuppe                 |                                                       |
|   2 | Tomatsuppe                      | Fjærland med far, Johannes og Vigdis                  |
|   3 | Pasta med sjømat i estragonsaus | Nils P laga i Fjærland                                |
|   4 | Ovnsbakt laksefilet             | I Fjærland                                            |
|   5 | Restar                          | Pasta frå Fjærland, med Bjørg Kristin og Andreas      |
|   6 | Fish and crisp                  | Med Bjørg Kristin                                     |
|   7 | Gulrotsuppe                     |                                                       |
|   8 | Ikkje middag                    |                                                       |
|   9 | Biff                            | Med bakt potet, tomat og sopp/lauk. Med Bjørg Kristin |
|  10 | Wok                             | Thai-inspirert med mango (!). Med Bjørg Kristin       |
|  11 | Hjortegryte                     | Bjørg Kristin laga. Med Bjørg Kristin og Andreas      |
|  12 | Rester                          | Rester frå helga. Med Bjørg Kristin.                  |
|  13 |                                 |                                                       |
|  14 |                                 |                                                       |
|  15 |                                 |                                                       |
|  16 |                                 |                                                       |
|  17 |                                 |                                                       |
|  18 |                                 |                                                       |
|  19 |                                 |                                                       |
|  20 |                                 |                                                       |
|  21 |                                 |                                                       |
|  22 |                                 |                                                       |
|  23 |                                 |                                                       |
|  24 |                                 |                                                       |
|  25 |                                 |                                                       |
|  26 |                                 |                                                       |
|  27 |                                 |                                                       |
|  28 |                                 |                                                       |
|  29 |                                 |                                                       |
|  30 |                                 |                                                       |

** 2019 

*** Januar
| Dag | Rett                        | Kommentar                                                     |
|-----+-----------------------------+---------------------------------------------------------------|
|   1 |                             |                                                               |
|   2 | Fisk i form                 | Rester frå romjula                                            |
|   3 | Gryterett                   | Aasmund middag jobb                                           |
|   4 | Pizza                       | Anna Lans 18-års dag                                          |
|   5 |                             |                                                               |
|   6 |                             |                                                               |
|   7 |                             |                                                               |
|   8 |                             |                                                               |
|   9 |                             |                                                               |
|  10 | Pastasalat                  | Rester frå arrangement på HVL                                 |
|  11 | Fingermat                   | Berit Rokne sin nyttårsfest                                   |
|  12 | Gryterett med potetstappe   | Bjørg Kristin bursdag, 18 personar                            |
|  13 | Pannekaker                  | Etter ønske frå Andreas                                       |
|  14 | Gryterett frå laurdag       | Aasmund                                                       |
|  15 | Pytt i panne grønskasrester | Aasmund                                                       |
|  16 | Pytt i panne med pølse      | Aasmund                                                       |
|  17 |                             |                                                               |
|  18 |                             |                                                               |
|  19 |                             |                                                               |
|  20 |                             |                                                               |
|  21 |                             |                                                               |
|  22 |                             |                                                               |
|  23 |                             |                                                               |
|  24 |                             |                                                               |
|  25 | Pølser og potetstappe       | Kveldsmat i Fjærland                                          |
|  26 | Taco                        | Med wienerpølser og vossakorv (Nils gløymte å kjøpe kjøtdeig) |
|  27 | Betasuppe                   | Med Bjørg Kristin, Claus, Nils, Haldor, Hans og Ivar          |
|  28 | Fiskeburger                 | Med Andreas i Kolstien                                        |
|  29 | Seibiff                     |                                                               |
|  30 | Omelett                     |                                                               |
|  31 | Fiskesuppe med boller       | Med Bjørg Kristin i Kolstien                                  |


*** Februar
| Dag | Rett                 | Kommentar                       |
|-----+----------------------+---------------------------------|
|   1 | Pasta med skinkesaus | Med Bjørg Kristin               |
|   2 | Betasuppe            | Haldor sin 3-årsdag i Arnafjord |
|   3 | Brosme               | Haldor sin 3-årsdag i Arnafjord |
|   4 |                      |                                 |
|   5 |                      |                                 |
|   6 |                      |                                 |
|   7 |                      |                                 |
|   8 |                      |                                 |
|   9 |                      |                                 |
|  10 |                      |                                 |
|  11 |                      |                                 |
|  12 |                      |                                 |
|  13 |                      |                                 |
|  14 |                      |                                 |
|  15 |                      |                                 |
|  16 |                      |                                 |
|  17 |                      |                                 |
|  18 |                      |                                 |
|  19 |                      |                                 |
|  20 |                      |                                 |
|  21 |                      |                                 |
|  22 |                      |                                 |
|  23 |                      |                                 |
|  24 |                      |                                 |
|  25 |                      |                                 |
|  26 |                      |                                 |
|  27 |                      |                                 |
|  28 |                      |                                 |
** Oppskriftar
| Namn                                | Kategori | Ingredienser                                                                                                                                                                                                                               | Framgangsmåte                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
|-------------------------------------+----------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Plukkfisk "Kari"                    | Middag   | Sei, poteter, rømme, purre                                                                                                                                                                                                                 | Kok poteter utan salt til dei er godt møre. Hell av vatnet, og legg eit par skiver smør oppå. Stapp dette saman slik at potetene er godt knust. Fisken (om lag like mykje som potetene i vekt) som er lettkokt i biter vert rørt inn i potetene. Spe med mjølk til passe konsistens. Bland inn grovhakka purre, og bland godt. Til slutt to-tre spiseskeier rømme, og smak til med salt. Server med smør, salt, pepper og flatbrød.                                                                                                                                                                                     |
| Rødkål etter Kvinner og Klær        | Tilbehør | 1,2 kg rødkål i strimler, 1 appelsin i båtar (press gjerne saften ut i starten), 2 epler i båtar, 4 kanelstenger, 1 vaniljestang (delt og skrapt ut), 12 pepperkorn, 150 g rørsukker, 2 løk i strimler, 1 chili i store biter, 2 dl eddik. | Bland alt og la det småkoke i 45 minutt. Legg på glass, fordel krafta.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| Boller                              | Anna     | 300 g sukker, 300 g smør, 1 l mjølk, 1,5 kg mjøl, 1 ts kardemomme, 1/2 ts salt                                                                                                                                                             | "Smelt smør bland i mjølk og varm til 375 °C. Bland inn sukker salt og kardemomme. Elt inn mjøl til litt laus konsistens. Dryss over mjøl og sett til heving. NB! fastare konsistens her gjev litt fastare deig å trille ut. Trill pølser (med meir mjøl) og boller. Hev 10 minutt pensle med egg og steik 10 minutt på 210 °C."                                                                                                                                                                                                                                                                                        |
| Lyse scones                         | Anna     | Ca. 12 stk: 300 g mjøl, 2 ss sukker, 1 ts vaniljesukker, 2 ts bakepulver, 1 1/4 dl mjølk, 75 g smør, 1 egg.                                                                                                                                | Bland alt turt, kna inn smør, bland inn væske. 2 cm tjukk deig, stikk ut med glas eller skjær i biter. 13 minutt 200 °C.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| Rømmegrøt                           | Middag   | 4 porsjonar: 6 dl seterrømme, 6 dl mjølk, 2 dl kveitemjøl.                                                                                                                                                                                 | Kok rømme i 2-5 minutt. Dryss i halvparten av mjølet under omrøring, og ta ev. av smør. Rør inn resten av mjølet og spe med mjølka. Det er ikkje sikkert du treng all mjølka. La koke ca. 5 minutt. Smak til med salt.                                                                                                                                                                                                                                                                                                                                                                                                  |
| Pizza grunndeig                     | Middag   | Ein pizza: 1,5 dl vatn, 3 ss olje, 4-5 dl mjøl, 1 ts salt, 1/4 pakke gjær.                                                                                                                                                                 | Bland alt godt, elt i 5-10 minutt, hev i minst 10 minutt. Kjevle ut. Steik på 230 °C i 12-15 minutt.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| Amerikanske pannekaker              | Middag   | 2 egg, 2,5 dl kefir, 1 ss smelta smør, 2,5 dl mjøl, 2 ts bakepulver, litt salt                                                                                                                                                             | Bland alt det blaute, bland inn alt det turre. Steik ca 1 minutt på kvar side.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Guacamole                           | Tilbehør | Avokado (mjuk) 3, tomat 2-3, chili 1/2, koriander, limesaft 1, salt, pepper, (litt lauk).                                                                                                                                                  | Mos (stavmikser er ok), finhakk og bland alt. Smak til med salt/pepper.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| Grove scones                        | Frukost  | Du trenger følgende til 8 scones: 4 dl sammalt hvete, fin, 2 dl siktet speltmel, 4 ts bakepulver, 1 ts salt, 1/2 dl havregryn, 3 ss rosiner, 3 dl tyrkisk yoghurt, 1 dl ekstra lettmelk                                                    | Bland godt sammen alle ingredienser (unntatt yoghurt og melk) i en bakebolle. Ha deretter i yoghurt og melk og rør godt sammen. Deigen skal være klissete. Bruk sleiv og skje til å fordele deigen til 8 store klumper på et smurt bakebrett. Stek scones’ene i ca. 15 minutter på 200-225 °C.                                                                                                                                                                                                                                                                                                                          |
| <<Pizza med brie>>                  | Middag   | 6 fiken, delt i skiver (ca. 5 mm), 4 ss balsamico eddik, pizzadeig, hjemmelaget eller ferdig kjøpt, 3 ss extra virgin oliven oil, 200 gram Brie de Paris, skivet, 70 gram prosciutto, skivet, 70 gram ruccola, vasket, havsalt, pepper     | Forvarm ovnen til 230 grader. Del opp fikenene og vend de i balsamicoen i en liten bolle. Kjevle ut pizzadeigen på et bakepapir og pensle deigen med 1 ss olivenolje. Fordel  skivet brie utover pizzaen og stek i 12-15 minutter til osten har startet å smelte og skorpen er lett gylden. Legg fiken på pizzaen og stek videre i 2-3 minutter til frukten har blitt lett myk. Ta pizzaen ut av ovnen og legg prosciutto utover. Bland sammen 2 ss balsamico med 2 ss olivenolje i en bolle. Vend dressingen inn i salaten og salt og pepre etter smak. Topp pizzaen med salat, del den i biter og server rykende varm |
| Sandefjordsmør                      | Tilbehør | 1 ½ dl fløte 100 g smør 1 stk sitron ¼ ts nykvernet salt ¼ tsnykvernet pepper 3 ssfinhakket bladpersille                                                                                                                                   | Kok opp fløte. Pisk inn små terninger med smør. Fortsett til alt smøret er pisket inn. Pass på at det ikke koker underveis, men at temperaturen ligger oppunder kokepunktet. Press saften ut av sitronen. Smak til med sitronsaft, salt og pepper, og tilsett bladpersille.                                                                                                                                                                                                                                                                                                                                             |
| Kylling med reker                   | Middag   | 4 kyllingfileter, pasta, 1 chili, fersk ingefær, pastasaus m/kvitlauk, grøn asparges, 200 g reker                                                                                                                                          | Brun filetane 2 minutt på kvar side, legg oppi chili og ingefær, la ligge under lokk i 8 minutt på middels varme. Lag pastasaus, server med kokt asparges og reker dryssa over.                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| Torsk i omn                         | Middag   | Til 4 personar: 800 g torskefilet, uten skinn og bein 1 stk purre 2 stilker selleri 2 stk gulrot 5 dl vann 12 stk cherrytomat 1 pose fiskesaus 100 g ost, revet salt og pepper timian, frisk                                               | Sett stekeovnen på 180 °C. Skjær torsken i serveringsstykker. Skjær purre og stangselleri i biter, og gulrot i terninger. Kok opp vann og kok grønnsakene i 2 minutter. Hell av vannet, og legg grønnsakene og cherrytomatene over i en smurt ildfast form. Legg torskestykkene over grønnsakene og dryss over litt salt, pepper og timian. Lag fiskesausen etter anvisning på pakken og hell den over fisken. Strø over ost, og stek retten i stekeovn i ca. 15 minutter.                                                                                                                                              |
| Corn relish                         | Tilbehør | Mais frå 10 kolber 2 raud paprika 2 grøn paprika 8 stilker selleri 1 stor gul lauk 10 dl epleeddik 5 dl sukker 1 ss sennepsfrø (eller 1 ts malt sennep) 3 ts salt 4 heile allehånde                                                        | Hakk alt fint, vask og skyll. Bland alt, kok i 30 minutt, fyll på glas (litt luft på toppen). Lukka glas 10 minutt i vannbad.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| Pannekaker                          | Middag   | 3 dl kveitemjøl, 2 ss sukker, 6 dl mjølk, 3 egg, 1/2 ts salt, 2 ss smelta smør                                                                                                                                                             | La røra svelle.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| Pottaske-kaker                      | Dessert  | 4 personer 125 g smør usaltet 125 g sukker  62.5 g sirup lys 1 ts pottaske 0.5 ss vann 1.75 ss kanel malt 1.25 ts natron 0.5 ts malt ingefær 45 g sukat 50 g mandler 250 g hvetemel                                                        | 1. Smelt smør, sukker og sirup over svak varme. Skal ikke koke. Avkjøl. Hakk mandlene 2. Rør ut pottaske i kaldt vann. Finner du ikke pottaske, kan du erstatte med natron. 3. Bland alle ingrediensene raskt i en kjøkkenmaskin. 4. Rull deigen til pølser. 5. Pakk i bakepapir og deretter i plast. 6. La rullene hvile i kjøleskapet minst til neste dag. 7. Skjær pølsene i papirtynne skiver. 8. Legg dem på bakepapir på stekeplate. Stek kakene ved 200 grader cirka 10 minutter til de er gylne. 10. Avkjøl på brett før du flytter dem over på rist. 11. Oppbevar i tett boks.                                 |
| Kylling på ris                      | Middag   | Tacokrydder (heimelaga?), raud/grøn/gul paprika, lauk (1 av kvar), kyllingfilet, ris, kyllingkraft som tilsvarer vatn til ris.                                                                                                             | Gni grønsakane med krydder, bland inn store fileter. Hell ris og kyllingkraft i ildfast form, legg grønnsakene og kyllingen oppå. Dekk med folie, steik på 200 °C i 50 minutt.                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Ramsløkolje                         | Tilbehør | Ramsløk, nøytral olje                                                                                                                                                                                                                      | Kjør en halv kilo ramsløk med 8dl nøytral olje i kjøkkenmixer. Varm opp til 75 grader i cirka 4 minutter. Sil av olje gjennom et klede. Da skal man ha en grønn olje som kan brukes som den er, eller til ramsløksmajones. Plantematerialet kan blandes med pinjekjerner og en god fastost. Salt, pepper og en god eddik gir en fin pesto. Majones: 1egg, 2eggeplomme og litt god eddik. Pisk luftig og tilsett ramsløkolje i tynn stråle til den tykner. Smak til med salt sukker og eventuelt eddik. Fin til sjømat og gode smørbrød!                                                                                 |
| Ramsløksmør                         | Tilbehør | Ramsløkssmør 100 g ramsløk 300 g rørossmør - romtemperert gjerne finrevet skall fra 1 sitron                                                                                                                                               | Kjør ramsløken et par ganger i en foodprosessor til det er finhakket. Tilsett mykt smør og sitronskall, og kjør videre til det er godt blandet. Sett smøret på kjøl slik at det blir fast igjen.  Tips: Vi har pakket smøret inn i bakepapir, rullet det som en pølse og avkjølt, slik at det kan skjæres i pene skiver når det er fast.                                                                                                                                                                                                                                                                                |
| Tacosuppe                           | Middag   | Kjøttdeig, bønner, tacosaus, tacokrydder, løk, mais, ost, rømme, chips ++                                                                                                                                                                  | Brun kjøtt, bland inn krydder, fres lauk og bland alt i gryte. Passe med vatn, mais i til slutt. Revet ost, rømme og chips attmed.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      |
| <<Torskefilet med grønkål>>         | Middag   | 2 personar: 400 g torskefilet, poteter, 4 blad grønkål                                                                                                                                                                                     | Legg grønkålblad i ildfast form, hell over olje. Legg torskefilet oppå, og varm i ovn (180 °C, 30 minutt). Dekk med folie mot slutten.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| Potetgraut                          | Middag   | Poteter, byggmel, mjølk, salt                                                                                                                                                                                                              | 500 g poteter kokt i stykker, hell av vatnet, stamp veldig godt. Spe med mjølk slik at 2 dl byggmel gir fast graut. Smak til med salt. La koke minst 10 minutt, til smaken av mjøl er vekk.                                                                                                                                                                                                                                                                                                                                                                                                                             |
| Sellerirotsuppe                     | Middag   | 2 personar: 1 gul lauk, 1/2 stor sellerirot, 1 liten søt paprika, 1 liten purre, 2 dl kokosmjølk, 3 dl kyllingbuljong.                                                                                                                     | Hakk lauk og paprika og fres i olje. Skjær sellerirot i tynne skiver og fres litt. Hell over 2 dl kokosmjølk, og etter ei lita stund buljong. Småkok i 20 minutt, mos med stavmikser og smak til med salt/pepper/chilisaus/... Server med litt bacon/pepperoni, og godt brød til.                                                                                                                                                                                                                                                                                                                                       |
| Gulrotsuppe                         | Middag   | 4 personar: 800 g gulrot, 400 g persillerot/pastinakk/sellerirot, 100 g raud paprika, 1 liter grønnsakkraft, urter, 1/2 sitron                                                                                                             | Kutt grønsaker og fres dei blanke i kjele med smør, ha i kraft, kok alt mørt, mos med stavmikser. Server med rista gresskarkjerner.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| Knekkebrød Johannes                 | Brød     | To brett: 4 dl sammalt spelt, 4 dl store havregryn, 2 dl solsikkefrø, 1 dl linfrø (knust), 1 dl sesamfrø, 1 ts salt, 6 dl vatn, 1 dl matolje                                                                                               | Bland alt, smør utover bakeplater, rut opp forsiktig. Steik på 150 grader varmluft i 70 minutt (byt plater etter 45 minutt), bryt opp, avkjøl.                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Søtpotetsuppe (Trines matblogg)     | Middag   | 4 personar: 400 g søtpotet, 200 g gulrot, 1 lauk (2 sjalottlauk), 3/4 chili, 2 ss revet fersk ingefær, 1-2 fedd kvitlauk, 1 boks (400 g) kokosomjølk, 5 dl buljong.                                                                        | Hakk alt i bitar, og la alt utanom søtpotetane bli blanke i ei gryte. Tilsett kokosmjølk mot slutten. Hell i buljong og søtpoteter. Kok i 20-25 minutt, mos med miksestav i gryta. Held seg i kjøleskap i fleire dagar.                                                                                                                                                                                                                                                                                                                                                                                                 |
| Lefser frå Dirdal                   | Dessert  | 750 g kveitemjøl, 250 g sukker, 125 g margarin, 5 dl kulturmjølk, 2 ts natron                                                                                                                                                              | Bland mjøl, natron og sukker, smuldre i smøret, bland i mjølk. Del i ca. 15 emner, rikeleg med mjøl rundt emnene. La stå kjølig over natta. Kjevle emna ut til ca. 3-5 mm tjukke (20 cm i diameter), steik på ca. 7 på takke. Ha litt smør på takka.                                                                                                                                                                                                                                                                                                                                                                    |
| Sylteagurker                        | Tilbehør |                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
| Gulrotkake frå Reddit               | Dessert  | 4 egg, 5 dl sukker, 5 dl kveitemjøl, 1 ts kanel, 1 ts vaniljesukker, 1-2 ts natron, 7,5 dl raspa gulrot, 2,5 dl matolje, hakka valnøtter. Fyll: 200 "Primula" (Smøreost frå Kavli), 200 melis, 133 g margarin/smør                         | Steik 200 °C ca. 45 minutt. Rør (pisk?) til jevnt fyll og smør på kald kake.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            |
| Pai med blåmuggost                  | Middag   | 100 g bacon, 2-3 løk (rødløk, gul løk eller store sjalottløk), i båter, 75-100 g blåmuggost, 3 egg, 3 dl melk, salt og pepper                                                                                                              | Steik bacon og surr lauk. Legg i paiforma, og hell egg/mjølk-blanding over. 200 grader 30-35 minutt.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| Pai med skinke, paprika og asparges | Middag   | 75-100 g god spekeskinke, 2 røde paprika, 1 rødløk, 2 fedd hvitløk, 6-8 asparges, 4 egg, 200 g creme fraiche, 2-3 ss parmesan                                                                                                              | Surr paprika, lauk, asparges og kvitlauk (finhakka/tynne strimler) til alt er mjukt. Legg i form, hell over egg/creme fraiche/parmesan-blanding. 200 grader 30-35 minutt.                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| Eplechutney                         | Tilbehør | 700 g  epler, 1 dl  appelsinjuice, 2 dl  honning, 2 dl  epleeddik, 1 stk  hvitløk, 1 ss  ingefærrot, hakket, 1 ts  karve, 1 ts  kanel, 1 ts  salt                                                                                          | Skjær eplene i bitar og bland alt i ei gryte, la småputre i 45 minutt. Avkjøl og legg på glas.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          |
| Sjokoladekake "Renate"              | Dessert  | Kake: 7,5 dl kefir, 6 dl sukker, 150 g smelta margarin, 10 dl kveitemjøl, 3 ss kakao, 1 ss natron. Glasur: 200 g smelta margarin (avkjølt, men flytande), 300 g melis, 1,5 ss kakao, 3 ts vaniljesukker, 3 ss kaffe                        | Kake: Bland alt, hell i langpanne (med bakepapir), steik 175 grader i 30+ minutt. Glasur: alt i kjøkkenmaskin, stryk på avkjølt kake.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
|                                     |          |                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                     |          |                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                     |          |                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                     |          |                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |
|                                     |          |                                                                                                                                                                                                                                            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         |


* Familie

** Kolstien

*** PÅGÅR Reparasjon av pipe 2019 <2019-05-28 tir.>
I originalanbodet står dette:
1. Oppsett av stillas og arbeidsplattform rundt pipe.
2. Ned vask av pipe og vegg.
3. På topp kant av pipe støpes en skrå kant. (for å lede vann bort fra pipe)
4. Pipe slemmes med 2 strøk slemme, (Maling anbefales ikke fordi den ikke slipper vann ut av mur konstruksjonen like godt).
5. Murvegg skrapes ren for løs maling, og grunnes og males 2 strøk.

Eg må sjekke punkt 3, og eg ber om at punkt 1 vert tatt vekk (dei hadde ikkje noko stativ som vi kunne sjå?) 

*** Nytt bad 2019

**** Skisse med omfang/type/... av arbeidet <2019-05-14 tir.>
 Thrond Holthe, 91151998
 thrond@hotmail.com

 Oppdrag:
  1. Rive gammelt bad, flytte veggar for å utvide, lage nytt bad. NB! Den eine veggen er bærande, så det må vurderes kva ein kan gjere her. Ca. 6 m2
  2. Legge inn nytt sluk i rom. Blindkjellar ikkje lett tilgjengelig, kanskje må betonggolvet brytast opp.
  3. Leggje nytt tregolv i eitt rom (ca. 9 m2)
  4. Leggje nye fliser med varmekabler i entre (ca 1,5 m2) 
  

** Sotra

*** Velforening

**** Styret

***** 2018
Leiar:   Terje Nordnæs, 41690718, 22116335712
Medlem:  Aasmund Kvamme, 
         Geir Trøen, 
         Magne Oddvar Skjelvik, 
Vara:    Yngve Nilsen,
Revisor: Gunnar Gundersen, 

***** Sotrasambandet
Aasmund tar kontakt med kommunen om reguleringsplan, og vegvesenet for informasjon.


** Songtekstar

*** 17. mai-hefte 

**** Oversikt [10/10]
 - [X] Norge i rødt, hvitt og blått
 - [X] For Bergen
 - [X] Fagert er landet
 - [X] Ja, vi elsker
 - [X] Gud signe vårt dyre fedreland
 - [X] Jeg vil verge mitt land
 - [X] Småguttenes nasjonalsang
 - [X] Blant alle lande
 - [X] Mellom bakkar og berg
 - [X] No livnar det i lundar

 Kjelder: https://www.hildes-hjoerne.com/35083706, http://www.17-mai.com

**** Tekstene
*Smaaguttenes nasjonalsang*

Vi ere en nasjon vi med, 
vi små en alen lange, 
et fedreland vi frydes ved, 
og vi, vi ere mange. 
Vårt hjerte vet, vårt øye ser 
hvor godt og vakkert Norge er, 
vår tunge kan en sang blant fler 
av Norges æres-sange. 

Mer grønt er gresset ingensteds, 
mer fullt av blomster vevet 
enn i det land hvor jeg tilfreds 
med far og mor har levet. 
Jeg vil det elske til min død, 
ei bytte det hvor jeg er fødd, 
om man et paradis meg bød 
av palmer oversvevet. 

Hvor er vel himlen mere blå? 
Hvor springer vel så glade 
de bekker som i engen gå 
for blomstene å bade? 
Selv vinteren jeg frydes ved, 
så hvit og klar som strøet med 
all stjernehimlens herlighet 
og hvite liljeblade. 

Jeg ikke vil for fremmed vår 
min norske vinter bytte, 
og fremmed slott ei nær forslår 
imot min faders hytte. 
Han sier han er der så fri. 
Det ei så nøye fatter vi, 
men noe godt er visst deri 
som verd er å beskytte. 


*Sønner av Norge*

Sønner av Norge, det eldgamle rike,
sjunger til harpens den festlige klang!
Mandig og høytidsfullt tonen la stige!
Fedrenelandet innvies vår sang.
Fedreneminner herlig opprinner
hver gang vi nevner vår fedrenestavn.
Svulmende hjerter og glødende kinner
hyller det elskte, det hellige navn.


*Norge i rødt, hvitt og blått*
 
Hvorhen du går i li og fjell, 
en vinterdag, en sommerkveld 
med fjord og fossevell, 
fra eng og mo med furutrær 
fra havets bryn med fiskevær 
og til de hvite skjær, 
møter du landet i trefarvet drakt, 
svøpt i et gjenskinn av flaggets farveprakt. 
Se, en hvitstammet bjerk oppi heien, 
rammer stripen med blåklokker inn 
mot den rødmalte stuen ved veien, 
det er flagget som vaier i vind. 
Ja, så hvit som det hvite er sneen, 
og det røde har kveldssolen fått, 
og det blå ga sin farve til breen, 
det er Norge i rødt, hvitt og blått. 

En vårdag i en solskinnsstund 
på benken i Studenterlund 
der sitter han og hun, 
to unge, nyutsprungne russ, 
to ganske nylig tente bluss, 
i 20 grader pluss. 
Hun er som en gryende forsommerdag 
som farves av gjenskinnet av det norske flagg. 
Ja, så hvit som det hvite er kjolen, 
og så rødt som det rø’ hennes kinn, 
hennes øyne er blå som fiolen, 
hun er flagget som vaier i vind. 
Han har freidig og hvitlugget panne, 
og en lue i rødt har han fått. 
Med en lyseblå tiltro til landet 
står vår ungdom i rødt, hvitt og blått. 

De kjempet både hun og han! 
Nå lyser seirens baunebrann, 
utover Norges land. 
Mot himlen stiger flagg ved flagg 
Som tusen gledesbål i dag, 
For alle vunne slag. 
Det knitrer som før over hytte og slott, 
Et flammende merke i rødt og hvitt og blått. 
Som et regnbuens tegn under skyen, 
Skal det evig i fremtiden stå. 
Se, det glitrer på ny over byen, 
I det røde og hvite og blå. 
La det runge fra gaten og torget, 
Over landet som nordmenn har fått: 
Du er vårt, du er vårt, gamle Norge! 
Vi vil kle deg i rødt, hvitt og blått!


*Mellom bakkar og berg*
 
Mellom bakkar og berg ut med havet
heve nordmannen fenge sin heim,
der han sjølv heve tuftene grave
og sett sjølv sine hus oppå deim.
 
Han såg ut på dei steinute strender;
der var ingen som der hadde bygd.
«Lat oss rydja og byggja oss grender,
og så eiga me rudningen trygt»
 
Han såg ut på det bårute havet,
der var ruskut å leggja utpå,
men der leikade fisk nedi kavet,
og den leiken, den ville han sjå.
 
Fram på vinteren stundom han tenkte:
«Gjev eg var i eit varmare land!»
Men når vårsol i bakkane blenkte,
fekk han hug til si heimlege strand.
 
Og når liane grønkar som hagar,
når det lavar av blomar på strå,
og når netter er ljose som dagar,
kan han ingen stad venare sjå.
 
Sud om havet han stundom laut skrida:
Der var rikdom på benkjer og bord,
men ikring såg han trelldomen kvida
og så vende han atter mot nord.
 
Lat no andre om storleiken kivast,
lat deim bragla med rikdom og høgd,
mellom kaksar eg inkje kan trivast,
mellom jamningar helst er eg nøgd.


*Blant alle lande*
 
Blant alle lande i øst og vest,
er fedrelandet mitt hjerte nest.
Det gamle Norge med klippeborge, 
meg huger best.
 
Fra Vesterhavet til kjølens rand,
fra Nordishavet til Kristiansand,
der har jeg hjemme og kan istemme: 
Mitt fedreland.
 
Jeg elsker eder I gamle fjell,
med høye tinder og dype vell.
Med skog om barmen og jern i armen 
til tidens kveld.
 
Jeg elsker alt som er ekte norsk,
fra folkelivet til sild og torsk,
som fremad skrider, om enn det glider, 
en smule dorsk.
  
Dog mest jeg elsker det folkeferd
som har sitt hjem mellom fjell og skjær.
Hvor unge hedre de gamle fedre 
som bygde her.


*Fagert er landet*
 
Fagert er landet du oss gav,
Herre vår Gud og vår Fader.
Fagert det stig av blåe hav.
Solli ho sprett og ho glader.
Signar vårt land i nord og sud,
soleis di åsyn lyser Gud,
yver vårt Noreg i nåde.
 
Tidi ho renn som elv mot os.
Fort skifter sumar til vetter.
Fader ver alltid Noregs los,
radt til dei seinaste ætter.
Herre vår Gud, vår Noregs Gud,
 varda vårt land frå fjell til flud.
Lær oss å gå dine vegar.
 
Signa då Gud vårt folk og land.
Signa vårt strev og vår møda.
Signa kvar ærlig arbeidshand,
signa vår aker med grøde.
Gud utan deg den vesle urt,
veiknar og visnar, bleiknar burt.
Ver du oss ljoset og livet.


*For Bergen*

Jeg tog min nystemte Cithar i Hænde,
Sorgen forgik mig paa Ulrikkens Top;
Tænkte paa Bauner, om de skulde brænde,
Og byde Mandskab mod Fienden op;
Følede Freden, blev glad i min Aand,
Og greb til min Cithar med legende Haand.

Værdige gamle graaskaldede Bierge,
I, som omgierde min Fædrene-Bye,
I, som saa mangen en Torden afværge,
Og sønderbryde electriske Skye!
Yndig er Dalen, I hegne mig ind,
Og Foraar og Dalen oplive mit Sind.

Herfra fortryllende Syner jeg skuer,
Lungegaards Vandet, den Slette saa blaa,
Nyegaards Alleens løvkronede Buer,
Derunder prydede Skjønne at gaae,
Deromkring Markens den festlige Dragt,
Det Guld i det Grønne den blomstrende Pragt.

Tæt ved mig Alrikstads dobbelte Slette,
Kongeborg fordum og brugbar til Strid,
Skjøn af Naturen om Fortrin vil trette
Med selve Nyegaard, som prunker ved Flid;
Der løb fra Svartedig skummende Aae,
Der saae jeg Møllehiul flittig at gaae.

Bedre frem Bergen, det Handelens Sæde,
Strækkende Arme om seilbare Vaag.
Derhen høifarmede Jægter med Glæde
Rustes hver Sommer til dobbelte Tog;
Derfra gaae Skibe saa vide om land;
Der kjøber, der sælger, der handler hver Mand.

Der seer jeg Skoven af Masterne høie,
Handlende Stuers bredvaiende Flag;
Vippebom seer jeg sig flittig at bøie,
Flittig at hæve. – Tangenternes Slag
Paa dette Handels- Claveer gav Musik,
Og Vare af Skuderne dandsende gik.

Nu tog jeg Vand af den springende Kilde,
Hvorudaf Oldtidens Kæmpeslægt drak.
Naar de lykønske sit Fødeland vilde,
Sverdet af Skeden tillige de trak;
Vee! den, saa sang de, saa synger jeg og,
Den Nidding, som Sverd imod Fødeland drog.

Freden o! Bergen! din Rede beskjerme,
Sommeren krone hver Ager med Brød!
Ilden og Sværdet Dig aldrig fornærme,
Havet Dig aabne sit frugtbare Skjød!
Da mellem Bjergerne syv skal Du staae,
Naar nybaget Kjøbstæd i Luften maa gaae.

Jeg drak den Skaal, som mig Ulrikken skjenkte,
Drikker den samme, I, som have Viin!
Hver, som oprigtig mod Fødebye tænkte,
Lod denne Munterheds Skaal være sin.
Held for vort Bergen, for Fødeland Held!
Gid alting maa blomstre, fra Fjere til Fjeld.


*Ja, vi elsker dette landet*

Ja, vi elsker dette landet,
som det stiger frem
furet, værbitt over vannet
med de tusen hjem.
Elsker, elsker det og tenker
på vår far og mor,
og den saganatt som senker
drømme på vår jord.

Norske mann i hus og hytte,
takk din store Gud;
landet ville Han beskytte
skjønt det mørkt så ut.
Alt hva fedrene har kjempet
mødrene har grett,
har den Herre stille lempet,
så vi vant vår rett.

Ja, vi elsker dette landet,
som det stiger frem
furet, værbitt over vannet
med de tusen hjem.
Og som fedres kamp har hevet
det av nød til seir,
også vi når det blir krevet
for dets fred slår leir.


*Gud signe vårt dyre fedreland*

Gud signe vårt dyre fedreland,
og lat det som hagen bløma!
Lat lysa din fred frå fjell til strand
og vetter for vårsol røma!
Lat folket som brøder saman bu,
som kristne det kann seg søma!

Og Noreg det ligg vel langt i nord,
og vetteren varer lenge;
men ljoset og livet i ditt ord,
det ingen kann setja stenge.
Um fjellet er høgt og dalen trong,
ditt ord heve då sitt gjenge.

So bløme vårt land i ljos og fred,
det grodde so grønt i lider.
Men atter seig natt på landet ned
med trældom og tunge tider.
Og folket det sukka etter ljos,
og du lyste upp umsider.

Og morgonen rann, og myrkret kvarv,
som lenge vår lukka skygde.
Du atter oss gav vår fridoms arv
og honom i trengsla trygde.
Du verna vårt folk og gav oss fred,
og landet med lov me bygde.

No er det i Noreg atter dag
med vårsol og song i skogen.
Um sædet enn gror på ymist lag,
det brydder då etter plogen.
So signe då Gud det gode såd
til groren ein gong er mogen!


*Jeg vil verge mitt land* 

Jeg vil verge mitt land, 
jeg vil bygge mitt land, 
jeg vil elske det frem i min bønn, i mitt barn, 
jeg vil øke dets gavn 
jeg vil søke dets savn 
ifra grensen og ut til de drivende garn. 

Her er sommersol nok, 
her er sedejord nok, 
bare vi, bare vi hadde kjærlighet nok. 
Her er diktende trang 
gjennom arbeidets gang 
til å løfte vårt land, blot vi løfter i flokk. 

Vi for vide på tog 
over gyngende våg, 
rundt i landene kneiser normanniske tårn. 
Men vårt modige flagg 
flyver vidre i dag, 
og det rødmer av sunnhet som aldri tilforn. 

Og vår fremtid er stor; 
ti det tre-kløvde Nord, 
det skal samles igjen, det skal blive seg selv. 
Hva du evner, kast av 
i det nærmeste krav, 
det skal bæres helt frem av en voksende elv. 

Denne bostavn er vår, 
og vi elsker den for 
hva den var, hva den er, hva den bliver igjen. 
Og som kjærlighet gror 
av den hjemlige jord, 
skal den gro av vår kjærlighets frøkorn igjen. 


*No livnar det i lundar*

No livnar det i lundar,
no lauvast det i li,
den heile skapning stundar
no fram til sumars tid.

Det er vel fagre stunder
når våren kjem her nord,
og atter som eit under
nytt liv av daude gror.

Guds ord vel alltid lyser,
den sol gjeng aldri ned.
Det hus som Anden hyser,
ligg støtt i ljos og fred.

Du vår med ljose dagar,
med lengting, liv og song,
du spår at Gud oss lagar
ein betre vår ein gong,

då me med vigsla tunge,
med kjærleik heil og klår,
alt utan brest og sprunge
skal lova Herren vår!



* Den norske kyrkja

** Ulike saker

*** Brev til BKF om administrasjonsleiaren [2019-02-17 sø.]
Til BKF v/Tove Margrethe Nordmark

Vi reagerer kraftig på meldingen om at Karin Skolseg slutter som administrasjonsleder og frivillighetskoordinator. De siste årene i Landås har vært preget av utskiftinger og "urolighet" i staben (både blant prester og andre ansatte); spesielt administrasjon/frivillighetskoordinator har vært preget av sykefravær og til dels manglende kompetanse. I 2018 opplevde vi at dette var blitt mye bedre. Etter at ny sokneprest og administrasjonsleder/frivillighetskoordinator ble tilsatt i 2017/2018 har staben jobbet svært bra sammen. Karin har utført sitt arbeid på en slik måte at de andre har kunnet konsentrere seg om sine arbeidsoppgaver. 

*Belastning for resten av staben*
At Karin nå slutter uten at en vikar er på plass vil skape store problemer i staben. I beste fall vil det være en del arbeidsoppgaver knyttet til hennes stillinger som ikke blir utført. Hun er også den som fordeler alle arbeidsoppgaver som ikke hører til en bestemt stilling. Det betyr at den eneste andre som da kan fordele slike oppgaver er soknepresten. Det vil svært fort føre til en urimelig belastning for henne. Det å fordele slike oppgaver krever en del lokalkunnskap om menigheten (som Karin har måttet bruke en del av sin tid til å bli kjent med), og det er ikke lett for en vikar å gå rett inn denne delen av arbeidet. Så i verste fall vil det være mye annet arbeid som ikke blir gjort.

*Rask saksgang*
Stillingen Karin har hatt ble lyst ut i 2017, og det har ikke skjedd noe etter det som tilsier en ny utlysingstekst. Så vi forventer at stillingen kan lyses ut så raskt som mulig.

*Oppsigelsestid*
Vi reagerer på at dette skjer så raskt. Menighetsrådets leder fikk muntlig beskjed 10. desember, og da var det allerede bestemt at Karin skulle slutte 1. januar. Vi mener det burde vært minst to måneder "oppsigelsestid" selv om det ikke er skifte av arbeidsgiver. Særlig når dette skjer i den kanskje mest hektiske tiden av året. Dette hadde skapt mer ro, og det kunne vært større sjanse for at en kvalifisert person kunne overtatt når Karin slutter.

*Våren 2019*
Landås menighet har en forholdsvis liten stab. Akkurat nå står vi uten prostiprest og administrasjonleder/frivillighetskoordinator, og staben består da av sokneprest (100 %), kantor (70 %), trosopplærer (30 %) og kirketjener (50 %). Prostipreststillingen vil bli betjent av vikarer hele våren, og denne mangelen på kontinuitet fører naturlig til belastning for de andre. Dersom administrasjonsleder/frivillighetskoordinator også er ubesatt (eventuelt bemannet av vikarer) vil belastningen bli urimelig stor for alle i staben. Vi vil ikke bli overrasket om belastningen blir så stor at vi får sykmeldinger.

På vegne av Landås menighetsråd
Aasmund Kvamme, leder


*** Soknerådsvalet 2019

**** Nominasjonskomite
 - Ragnar Tvinnereim (ja)
 - Jan Frode (ja)
 - Odd Helge
 - Ingrid Drange
 - Heidi Westlie
 - Åse Åtland
 - Gunvor Eikil (ja, leiar)

Kan vi ha eit innlegg på Helgatun? Om korleis det er å sitje i soknerådet. Kort liste over kva saker vi har hatt (spennvidden frå offerliste til tilsetjing av sokneprest, via parkeringsplasser for Lystgården og innsamling av pengar til ungdomsarbeider).
Kan eg også sei noko om "satsingsområde" framover? Kven har vi altså bruk for no?

- Artikkel på nettsidene
- Brosjyre på [[https://kyrkja.no/nn-NO/om-kirken/slik-styres-kirken/kirkevalget/kirken-trenger-deg/][kyrkja.no]] (lag denne for Landås i InDesign)
- Sjekk også [[https://kyrkja.no/nn-NO/om-kirken/slik-styres-kirken/kirkevalget/Kirkevalget-enkelt-fortalt/]["Kyrkjevalet oversikt"]]
- [[http://trykksak.kirken.no/login.aspx?ReturnUrl=%2f][trykksak.kirken.no]] - logg på og lag trykksaker

Kan "Vel bevart" vere stemmelokale (forhåndsstemmer)?

Vi må trykke stemmesetlane sjølve

Kan vi bruke Facebook?


**** Liste
| Plass | Namn                     | E-post                       | Telefon |
|-------+--------------------------+------------------------------+---------|
| Fast  | Bjørg Møllerløkken       | bjorg.mollerlokken@gmail.com |         |
| Fast  | Johannes K Selvik        | joseeko@gmail.com            |         |
| Fast  | Gunvor Vestbøstad Eikill | gunvor.eikill@gmail.com      |         |
| Fast  | Andreas Tveit            | andreas@tveit-lys.no         |         |
| Fast  | Irene Eikeland           | irene.eikeland@icloud.com    |         |
| Fast  | John-Helge Heimdal       | john.heimdal@helse-bergen.no |         |
| Fast  | Torill Tufteland         | Messenger                    |         |
| Fast  | Torgeir Storaas          | torgeir.storaas@gmail.com    |         |
|       |                          |                              |         |
| 1     | Kari B Davidsen          | kari.barca.21@gmail.com      |         |
| 2     | Marianne Lande-Sudall    | Messenger                    |         |
| 3     | Jarle Kallestad          | jarle.kallestad@hotmail.com  |         |
| 4     | Helga Bjørnøy Urke       | helgaurke@gmail.com          |         |
| 5     | Eirik Kvalbein           | Messenger                    |         |


*** Kapellan 2019

**** Søknadsteksten
Kapellan i Landås sokn – prostiprest i Bergensdalen prosti 
Den norske kirke, Bjørgvin bispedøme
Det er ledig stilling som kapellan i Landås menighet og prostiprest i Bergensdalen prosti. 

Menighet søker en engasjert kapellan som kan være med å arbeide for menighetens visjon: Med himmel i blikket og jord under føttene. https://kirken.no/landas 

I kirkens nabolag, som ligger ved Ulrikens fot, finner man blant annet gjenbruksbutikken «Vel bevart» som drives i samarbeid med to andre menigheter, stiftelsen Lystgården og Bærekraftige Liv på Landås, samt en av landets største speidergrupper. Menigheten ønsker å være en miljøbevisst, aktiv deltager i lokalsamfunnet, og kunne tilby et åpent kirkerom for mennesker i alle aldre. 

I Landås sokn i Bergen bor det omlag 6500 mennesker, hvorav ca. 4500 er medlemmer i Landås menighet. Det bor også mange studenter i området. Det ligger en skole i menigheten, Nye Landås skole (åpnet i 2016), med ca. 450 elever. Kullene øker stadig, da mange barnefamilier de siste årene har bosatt seg på Landås. 

Menigheten har ulike aktiviteter og mye frivillig innsats. Barne- og familiearbeidet er særlig oppegående med juniorklubb, flere kor, speiderarbeid, søndagsskole og åpen barnehage. Flere av disse gruppene er tilknyttet KFUK/KFUM - som menigheten samarbeider godt med. På «Supermandag» serveres det ukentlig middag. Gudstjenestene er en møteplass for hele menigheten, der blant annet kirkekoret og frivillige musikere deltar regelmessig. Det er god oppslutning og engasjement rundt familiegudstjenestene. En gang i måneden er det seniortreff. 

Det er 30-40 dåp i året, rundt 30 konfirmanter og omlag 70 gravferder i Landås menighet. Prestene besøker to eldresentre og menighetsbarnehagen regelmessig. Prestene deler på tjenesteuker, konfirmantarbeid og øvrig menighetsarbeid. 

Kapellanen vil ha kontor og være tilknyttet staben i Landås. Den består av sokneprest (100%), administrasjonsleder 60%/frivillighetskoordinator (30%), kantor (70%), kirketjener (50%) og menighetspedagog (30%) 

Kapellanen vil også tjenestegjøre som prostiprest i Bergensdalen prosti. 
Foruten Landås, består prostiet av Slettebakken, Fridalen, Årstad, Løvstakksiden, Storetveit, Bønes, Sælen og Fyllingsdalen. 
Prosten leder prestetjenesten i prostiet og vil til enhver tid koordinere prestens arbeidsdeling mellom Landås menighet og tjeneste som prostiprest. 

Bergensdalen prosti har et godt kollegafelleskap og prestene har jevnlige møter, der faglig utvikling, åndelig felleskap og godt kollegafelleskap står sentralt. 

Vi gjør oppmerksom på at opplysninger om søkerne kan bli offentliggjort selv om søker ber om å bli unntatt offentlig søkerliste. Opplysninger om samlivsform vil kunne bli innhentet og vektlagt ved tilsetting. 
Den som blir tilsatt, må vise tilfredsstillende politiattest (barneomsorgsattest jf. politiregisterloven § 39). Søker må ha førerkort klasse B og bør disponere bil. Beredskap etter gjeldende regler. 

Vi ber om at søknad med CV, vitnemål og referanser sendes elektronisk via Webcruiter.

*Arbeidsoppgaver*
 - Soknepresten i Landås fordeler gudstjenesteuker, tjenesteuker og institusjonsbesøk mellom kapellan og sokneprest.
 - Både kapellan og sokneprest deltar i konfirmant- og trosopplæringsarbeidet.
 - Som prostiprest vil arbeidet innebære gudstjenester, kirkelige handlinger og andre vikaroppgaver i prostiets øvrige kirker. Prosten lager regelmessige planer for dette arbeidet.

*Kvalifikasjoner*
Vi ønsker oss en kreativ prest 
 - som setter pris på å arbeide med barn og unge
 - som evner å kommunisere med mennesker i alle aldre
 - som liker å jobbe med de frivillige
 - som er glad i å arbeide med gudstjenesten og de kirkelige handlinger

Gode samarbeidsevner og personlig egnethet vektlegges
Utdanningsnivå
Cand. theol. med praktikum eller tilsvarende
Mastergrad i teologi og praktikum
Vi tilbyr
Stillingen er plassert i stillingskode 0922 kapellan, med pensjonsinnskudd i Statens pensjonskasse
Godtgjørelser blir gitt etter til enhver tid gjeldende reglement
Den som blir ansatt får tilbud om arbeidsveiledning


*** Bispedømerådsvalet 2019

**** Kontakt med andre komitear:
Oslo: einwald@gmail.com, 908 25 553
Hamar: sjekk e-post


**** Oppsummering av ny liste 28. april
Avstemming per e-post

| Stemme nr | Namn       | Stemme til liste | Kommentar                          |
|         1 | Anne Grete |                3 |                                    |
|         2 | Reidun     |                3 |                                    |
|         3 | Jorunn     |                3 |                                    |
|         4 | Rune       |                3 |                                    |
|         5 | Hanne      |                4 | Annankvar kvinne/mann              |
|         6 | Tove       |                4 |                                    |
|         7 | Rune       |                4 |                                    |
|         8 | Dagfinn    |                2 | No var Daniel sine svar kommet inn |
|         9 | Liv Jorunn |                4 |                                    |
|        10 | Helge      |                2 |                                    |
|        11 | Liv Jorunn |                2 |                                    |
|        12 | Rune       |                2 |                                    |
|        13 | Hanne      |     Ingen stemme | Ønske om Daniel opp, kvinne nr 2   |
|        14 | Jorunn     |                2 |                                    |
|        15 | Reidunn    |                5 | Per Hilleren og Daniel opp         |
|        16 | Hans Atle  |                2 |                                    |
|        17 | Dagfinn    |                5 |                                    |


**** FERDIG Notat til neste nominasjonskomite <2019-05-15 on.>
Etter ønske frå nominasjonskomiteens liste, i møte 14. mai 2019:
1. Nominasjonskomiteen bør setje yngre kandidatar høgare opp, minst ein ungdomskandidat blant dei fem første. Dette for å markere at kyrkja verkeleg satser på dei yngre.
2. Nominasjonskomiteen bør, så langt råd er, kommunisere med den enkelte nominerte for å avklare kva plass den enkelte kunne tenkje seg å stå på.


*** Ungdomsarbeidet

**** Åse Kristin
Vi må gi Mari lønn for å avhjelpe Kjetil med ungdomsarbeidet til neste år. Dersom vi ikkje får nokon til å drive med Ten-sing frivillig må vi vurdere kro mykje det skal vere. Kanskje Ulriken kan bidra her?

**** Jan Frode
Det er ikkje godt ungdomsarbeid å lønne Mari for å hjelpe Kjetil, for dette bør ligge i hans stilling. Vi bør heller satse på Ten-sing med menighetens midler. 

**** Aasmund
Kva er vanleg rundt omkring? Kva med samarbeid på tvers av menighetsgrenser?

 
*** Giverteneste
Mogleg person som kan vere pådrivar: Lars Hopland Nestås, Øvre Kolstien 3 A, telefon: 


*** PÅGÅR Menighetsbladet <2019-05-23 to.>

**** Tekst til nettsidene/Facebook
Redaksjon i menighetsbladet

Landås menighet trenger en redaktør og en redaksjon i menighetsbladet, så snart som mulig.

Landås menighet har i dag ingen redaksjon i menighetsbladet. Det betyr at det ikke kommer ut noe blad; alle informasjon skjer nå gjennom nettsidene og Facebook. Vi ønsker derfor at du som har interesse av at det kommer ut et blad, og som også kan tenke deg å bidra på en eller annen måte, tar kontokt med oss. Vi trenger noen som kan 
- være redaktør
- skrive artikler og skaffe stoff
- lage bladet (layout)
- selge annonser eller skaffe penger på annen måte 

Om bladet fortsatt skal komme ut så ofte som i dag, og i samme format som i dag, eller om mer skal legges på nettet, vil den nye redaksjonen kunne være med og bestemme i samarbeid med menighetsrådet.

Ta kontakt snarest med kirkens stab (...@kirken.no) eller menighetsrådsleder (aasmund.kvamme@gmail.com), så kan vi få til en redaksjonkomite. Takk for at du melder deg!


*** PÅGÅR Brev til biskopen
Send [[https://www.dropbox.com/s/vn2afhcm1kavy9n/P%C3%A5skegudstjenester%20i%20Land%C3%A5s%20kirke.docx?dl=0][skissa]] til Åse Kristin til uttale/utfylling

**** Originalbrevet (av [2019-05-13 må.])
Påskegudstjenester i Landås kirke

Til Bjørgvin biskop,

Landås menighetsråd ønsker å uttale om gudstjenester i påskehøytiden:

Bakgrunn
Påsken er den mest sentrale høytiden i kirkeåret, og gudstjenestene i påsken [fyll inn litt argumentasjon her?]. En fullsatt kirke på disse viktige dagene er blant det aller mest menighetsbyggende vi har. 
Samtidig er Landås menighet preget av mye innflytting, og mange har familie andre steder i landet. Mange tar derfor ferie i den stille uke og/eller påskedagene for å besøke familie. Dessuten har mange i menigheten hytte/landsted, og mange er på hytta.
Disse to faktorene gjør at gudstjenestene særlig Skjærtorsdag og Langfredag har svært få deltakere. Se statstik i tabellen. (Men også Påskedag har få deltakere, og som en konsekvens av dette har Landås i flere år feiret oppstandelsen første søndag etter påske. I 2019 var det «Barnas oppstandelsesfest» med over [fyll inn tall her] små og store.)

Samarbeid med nabomenigheter
For å kunne gi de som søker til kirken Skjærtorsdag og Langfredag en god opplevelse ønsker vi muligheten for å kunne samarbeide med nabomenigheter om å ha gudstjenester disse dagene, alternativt at Landås kan vise til gudstjenester i disse menighetene. 
Vi tror at opplevelsen av gudstjenesten vil være mye større når man kan feire i et større fellesskap enn når det er seks deltakere i en «tom» kirke. Det vil dessuten koste mindre [skal vi ha med den setninga????]

Bergen, xx. juni 2019

For Landås menighetsråd,
Aasmund Kvamme, leder



** Årshjulet
Vedtatt i desember 2017:

| Måned     | 	Viktige saker                                                   |
|-----------+-------------------------------------------------------------------------|
| Januar    | Offersøknader/budsjett                                                  |
| Februar   | Årsavslutning regnskap, årsmelding og årsplan                           |
| Mars      |                                                                         |
| April     | Forslag til fellesrådet sitt budsjettforslag til kommunen               |
| Mai       | Haustprogrammet                                                         |
| Juni      | Vurdering av arbeidet i halvåret                                        |
| August    | Medarbeidarsamling                                                      |
| September | Kyrkjelydsbladet/informasjonsarbeidet, gjevartenesta, rekneskapsrapport |
| Oktober   | Trusopplæring og barne- og ungdomsarbeidet                              |
| November  | Målsetjing for neste år                                                 |
| Desember  | Vurdering av halvåret, planar/budsjett, val og oppnemningar             |

Rullert i desember 2018: inga endring


** 2018
*** Januar
  torsdag 16. november 2017
  20:50
 
  •	ÅKNA ønsker at vi i januar tar opp generelt om gudstenestelivet
  •	Budsjett - med ønske frå Jan Frode
  •	Møteplan for våren med tema
  •	Avklaring om roller/planar i ungdomsarbeidet
  •	Spør Toril om overlapp med Karin
  •	Innsetjing av Kristin Lødøen Hope sundag 14. januar
  Møteplan for 2018
 
  Onsdagar er det nokre som har bibelgruppe.
  Torsdagar har Åse Kristin konfirmantar?
 
  Sokneråd	Arbeidsutvalet	Hovudsak
  Torsdag 18. januar	Onsdag 9. januar	Budsjett, gudstenesteliv
  Torsdag 22. februar	 	Høyring om virksomhetsgjennomgang, årsmelding og årsrekneskap
  Torsdag 22. mars	 	Givertenesta
  Torsdag 19. april	 	Planlegge haustprogrammet
  Torsdag 24. mai	 	Framlegg til fellesrådets (langtids)budsjett
  Torsdag 14. juni	 	Mat og kos
  Torsdag 30. august	 	Planlegge medarbeidersamling
  Torsdag 20. september	 	Sjå på menighetsbladet/informasjonstenesta
  Torsdag 18. oktober	 	Trusopplæring/barne- og ungdomsarbeidet
  Torsdag 15. november	 	Planar for 2019 (val i september)
  Torsdag 13. desember	 	Budsjett 2019, konstituering
 
 
  Saksliste
  1/18 Godkjenning av innkalling
  2/18 Referat frå førre møte
  3/18 Orientering om stabssituasjonen (Karin Skolseg, Annicken permisjon (Toril vikar), og nøkkelsituasjonen
  4/18 Møteplan for 2018
  5/18 Budsjett 2018
  6/18 Vaskemaskin til kjøken
  7/18 Temadagen 10. februar: innhald/program
 
  Forfall
  Ane Kvaal, tenestereise
 
  Temadagen
  1.	"Bli kjent" med Karin
  2.	Gudstenestelivet 
*** Februar
  tysdag 9. januar 2018
  20:26
  Inspirasjonssamling
  Frå Eileen
  Tanker/ønsker for Landås menighet: 
  Her er det svært mykje å ta tak i. Me har for tida ein tilsynelatande vellukka menigheit, men som berre er det for nokon. Ein menigheit kor det førekjem både mobbing og utestenging, hersketeknikkar og at ikkje alle er gode nok. 
  Eg ønskjer at menigheita skal bli meir inkluderande og tilgjengelig for alle. At me får bukt på gjeng/gruppe-danninga kor enkelte står innanfor i det gode selskap, mens andre ikkje er gode nok. At me blir flinkare til å sjå kvalitetar/gåver/evner hjå alle, og ikkje berre bruker dei same folka om igjen og om igjen. At mobbing i menigheita ikkje skal og bør førekoma. At menigheitsrådet blir ein stad kor gode idear og gode diskusjonar kan få plass og rom, og ikkje berre blir dytta ned og latterliggjort av dei andre. 
 
  I tillegg har eg ein draum om å få til familiekoret igjen, sånn som det var på sitt beste. Det var ei oppskrift som fungerte, det var lett å rekruttera folk, det var opent og velkomment. Eg trur svært mange familiar tidligare verkelig har følt seg velkomne då dei kom inn i familiekoret. Det må tilbake til å vera på laurdagar som det var. 
  Supermåndag er vel og bra, men alle kan ikkje vera med på dette i ein vekedag. Så for nokon vil det jo aldri passa. Me har og prøvd diverse andre aktivitetar/arrangement samstundes med kor, som band/leiking/superlaurdag mv. Dette har vore meir eller mindre vellukka, men krev for mykje og sklir berre ut igjen. Familiekoret som det var, var så enkelt og genialt, at det dreiv seg sjølv. 
 
  Konfirmasjonsopplegg som faktisk fenger og trekker ungdommen, eller legge inn årene og heller samarbeida med ungdomsklubbane i Storetveit og Slettebakken. Der har dei i alle fall fått til eit opplegg som både fenger og kor ungdommane frivillig blir lengre. Eg trur ikkje Landås er stort nok for å halda på ungdommane over konfirmasjonsalder. Tensing-kor er kjekt for dei som liker det, men når det blir tvang fører det til at til og med dei som kunne likt det, ikkje liker det av di dei må stå der saman med ein haug som eigentlig ikkje liker det. Eg har fått svært mange negative tilbakemelingar på konfirmasjonsarbeidet i Landås både i fjor og i år. Tensing kan ev vera eit alternativ dei kan velga, men kan aldri åleine bli eit fullverdig konfirmasjonsarbeid for eit heilt kull. 
 
  Høyring om virksomhetsgjennomgang
  Be Aina om å referere ein gang til. 
  Høringsbrev
 
  Aina refererer til at det er sprikande meiningar
 
 
 
  Orientering frå fellesrådet/LME
  Hugs å alltid ha dette oppe.
 
  Saksliste
  1.	Virksomhetsgjennomgangen
  Aasmund starter på ei uttale, som går på sirkulasjon til dei andre i "god tid" før møtet.
  2.	Årsmelding
  Aina har starta på innleiinga. 
  Dato for årsmøte: onsdag 4. april
  3.	Brevet frå Eileen: Vi har svart henne, og det er opp til henne å gå vidare. Ingen treng kjenne på at dei burde gjort meir.
  4.	Menighetsbladet: "Kva skjer i menigheten?" Gaute ønsker seg meir stoff, og at menigheten kjøper inn eit kamera som kan vere brukt til at "alle" kan ta bilder. Fridalen ønsker eg eit samarbeid om "informasjonsstrategi". Åse Kristin svarer han.
  5.	Orientering: 
  a.	Kirkesølvet kan under ansvar lånes ut.
  b.	Samarbeid i påsken. Åse Kristin orienterer om møte i prosti.
  c.	KNs fasteaksjon. Soknerådet vert oppmoda om å stille som bøssebærarar.
  d.	Kyrkjekaffe: vi revurderer ordninga vi har no. Litt meir enn Mariekjeks?
  e.	Prosesjonskors? Aasmund es eldre referat.
  f.	Ryddedag. ÅK ønsker ein fast "ryddedag" der sokneråd / frivillige samles til mat/rydding.
*** Mars
  tirsdag 13. mars 2018
  15:11
 
  Oppfølging av Aasmund
  1.	Møte rett etter påske om ungdomsarbeidet. Vi må avklare kva som er planlagt og avtalt. Kven har arbeidsgiveransvar? 
  Doodle til Mari, Karin, Jan Frode og meg om møtedato
  2.	Kva gjer vi med Frifond-midler? Og TenSing? Skal vi "forlange" at pengane vert overført til menigheten, for at vi kan definere korleis dei vert brukt? Alternativt: vi budsjetterer ikkje med desse pengane, men mister vi då kontrollen over dette arbeidet?
*** April: 18. april
  tirsdag 13. mars 2018
  15:11
 
  Saksliste
  •	Evaluering av påsken 2018: samarbeid med dei andre i prostiet.
  •	Planlegging av neste års gudstenestliv.
  •	Kyrkja si heimeside inn på kirken.no? Sjå saksdokumentet.
  •	Nestleiar - 
  •	Giverteneste - kven skal vere ansvarleg?
  •	Kirketjener - søkerliste
  •	Kapellan - Kristin har fått 50 % på Haukeland sjukehus. Vikar: Nina Nn (som bur i menigheten, to små barn) Orientering om saken.
*** Mai: 24. mai
  onsdag 11. april 2018
  15:34
 
  Saksliste
  •	Kirkevergen blir kjent med Landås
  •	Haustprogrammet med vekt på samarbeid med dei ulike gruppene
  •	Hilde sluttar i barnekora - kva gjer vi vidare?
  •	Avtale om å disponere parkeringsplassen
  •	Orienteringer
  o	Avskjed for Toril? Kyrkjekaffien 27. mai?
  o	Avskjed for Lene 27. mai
  o	Ny kirketjener - vi går for Joakim.
  o	Referat frå LME og BKF
  o	Sommerkonsert v/Carina Bless
  o	Ingen Madagaskar-tur
  •	Økonomi
  o	Tertialrapport dersom den er klar
  o	Orienterer om at vi i juni-møtet skal ta opp budsjett 2019 i BKF
*** Juni: xx. juni
  tysdag 15. mai 2018
  13:42
 
  Saksliste
  Budsjettønsker for 2019
*** August: 
  torsdag 13. september 2018
  20:04
*** September: 20.9
  torsdag 13. september 2018
  20:04
 
  Etter årshjulet: menighetsblad og informasjonsarbeid (dette tok vi i august)
 
  Under eventuelt: parkering
*** Oktober: 18.10
Etter årshjulet: barne- og ungdomsarbeid
Det passer å invitere Gunhild Felde til å snakke om sundagsskulen.
Og Hilde T S om trusopplæring. Aasmund snakker med Hilde om stillingsbeskrivelsefør dette.
 
Andre ting:
 * Økonomirapport med VIPPS-rapport [Karin kan lage "varelinjer" for ulike formål, slik at vi kan spesifisere inntektane]
 * Givertenesta fungerer frå 1. november
 * Temamøte om ny kirkeordning 26. november (e-post)
 * Bøssebærere sundag (e-post)
 * Budsjettarbeid

**** Gunhild orienterer om sundagsskulen
Det er ofte mellom 20 og 30 born på sundagsskulen. Når dei yngste (Gulliver, opp til skulealder) og (ofte) dei mellomste (Tårnagenter, 1.-4. klasse), men klarer det ikkje alltid.
Lokala er også eit problem; først og fremst lufta, men også innreiinga.
Ho brenn verkeleg for arbeidet, og har som visjon at det skal vere eit team med leiarar. 

Debatt:
Kan vi gjere noko med menighetssalen for at den (lett) kan brukast til dette og andre aktivitetar når kjellaren er så dårleg?
Vi bør rydde opp i bruken av dei ulike romma; mellom anna speideren sin bruk av det midterste rommet, og dei andre romma til turking.
Kan vi få vindu i sundagsskulerommet? Glasdør?
Kan sundagsskulen disponere eitt av romma? Kunne vi fått betre ventilasjon i det innerste rommet?

1. Definere bruk/behov
2. Avklare lufting
3. Bestille interiørarktiekt?

**** Stillingsbeskrivelse for menighetspedagog
Viktig at innhaldet i stillinga vert sett i samband med ein ev. ny kapellanstilling.
Kan vi formulere oss slik at nokre av desse punkta kan bli lagt til kapellanstillinga?
 
*** November: 15.11

**** 70/18 Menighetspedagogen

**** 71/18 Kapellan
Rose-Marie har sagt opp. Dersom ho vil det å vert det ei avsluttingsgudsteneste med henne og Anne Mathilde. Prosten tar kontakt med henne.
Nina har siste gudsteneste 16.12; soknerådet markerer dette i gudstenesta.
Vikar for våren:
I følge Cathrine Waaler Halstensen går det mot ei utlysing av stillinga. Fint om vi uttaler oss om kva vi har lyst til og sender til Cathrine.
Karin/Åse Kristin tar utgangspunkt i utlysinga til sokneprest frå 2017, og skriv denne om i samarbeid med Aasmund.


**** 72/18 Fest for frivillige
Auker rammene for mat. Staben tar opp om det skal vere underhaldning.

**** 73/18 Orientering

***** Samarbeid/organisering [Aasmund]
Lite nytt konkret frå møtet i Eidsvåg.

***** LME [Aina]
Frustrasjon frå LME over kommunen si saksbehandling av utbygging/ombygging.

***** Menighetsbladet [Karin]
Nokre litt store ruter; kan vi dele opp, kan vi be om fleire? 

***** Kommunisere dåp, "Dåpsløftet"
Dåpstala er på veg ned; i må informere. Plakat på helsestasjonen?

***** Allehelgen/Minnegudsteneste
Stemninga er for at vi les høgt namna på /alle/ i ei vanleg gudsteneste.

***** Julegudstenesta
To gudstenester vert for mykje for organisten (etter på LME). Men Åse Kristin har lyst til å arbeide vidare for det på sikt. Kanskje ta vekk den frå LME.

***** Radiogudstenestene 2019
10/2, 26/5 og to til hausten (familiegudsteneste).

***** Nattverd ved store gudstenester
1) Treng vi to til å dele ut nattverdsvin? Kanskje/kanskje ikkje. Bjørg ønsker fleire salmer. Mette ønsker at vi nevner bønnevandring.
2) 

***** Prosjektkor 22.12
Melanie har varsla at musikk er avhengig av støtta frå kommunen.

  Etter årshjulet: 

  Saker:
   * Revidere årshjulet (desember)
   * Budsjettførebuing (innspel frå soknerådet)
   * Høyring om kyrkjeordninga: Aasmund melder inn dersom det er ting i høyringa som er /veldig/ forskjellig frå i dag. Aasmund svarer på vegne av Landås.
   * Vedtakssak: Åse Kristin ønsker at vi skal lyse ut kapellanstillinga. Kristin Litlere kjem kanskje til å få tilbodet om denne, men ho vil helst bli sokneprest og då meiner ÅK at det er betre å lyse ut med vikar i eit havt år enn å tilsetje ein prest som allikevel kjem til å søke seg vekk.
   * Karin går litt parallelt på BKF i sentrum (vikariat). Ho får også opplæring på den måten. November - Januar (?)
   * Vedtak: Stillingsbeskrivelse for menighetspedagog
   * Aasmund tar med framlegg til innstikk om tekst til giverteneste
   * Innspel om at det vert ei eiga minnegudsteneste for dei døde, ikkje inne i den vanlege gudstenesta. I forlenging av dette: det vert ei gudsteneste julekvelden 2018.
   * Datoar på radiogudstenestene
   * Menighetsbladet: vi treng fleire til å bære. Gaute har lyst til å gi ut eit blad før jul - har vi råd? Han vil ha fleire med i redaksjonskomiteen.
   * Nattverd: kan vi tenke om det er mogleg å ha to til å dele ut vin, og ein (kyrkjevert) som kan hjelpe med å vaske opp.
   * Dåpsløftet, informasjonshefte
   * Fest for frivillige 8. januar 2019


*** Desember: 13.12
Saksliste:

**** Konstituere rådet for 2019
Aasmund leiar, Bjørg nestleiar


**** Utlysing kapellan


**** Vedta budsjett for 2019
Vi deler ut "Budsjett 2019 framlegg til soknerådet" til møtet saman med kommentarne. Det endelege budsjettet vert ført i "Budsjett 2019 - Landås"
***** Budsjett - kommentarar til 2019

****** Kontoplaner

******* Ulike konti

******** Avdeling 2000 Menighetsrådet
    3111 Får ein del frå 3127
    3122 og 3124 slåes sammen
    3127 deles til 3111 (blomar til gudstenesta) og 3126 (blomar som gåve). Resten i 3127 er blomar til kontor og ute.
    3135 Karin har rydda i bankavtaler
    3151 Ført på andre avdelingar
    3203 Lågt budsjett, for vi har jo sagt vi skal over på vegg, og vi har alt kjøpt salmebøker!
    3262 Dugnadsinnsats frå Karin på konfirmantkappene
    3260/64 Justere litt her; ein del av 3260 er containere og makulering, som høyrer inn under 3264
    3270/1/2 Kunne desse vore slått saman?
    3471 Manglande konfirmantbetaling
    3867 Kan saneres; går inni 3866
    3941 Dette er pengar vi tar frå fond!

******** Avdeling 2200 Trosopplæring  
    3111/3272 Går opp i kvarandre (er honorar til klovner 3111 eller 3272?)
    3873 Kan vi fordele givertenesta etter ein nøkkel?

******** Avdeling 3500 Menighetsbladet
   Generelt: det er eit veldig flott og dyrt blad. Vi får ikkje delt det ut heller ...

******** Avdeling 4100 Konfirmanter
    3055/3262 skal sjåast under eitt
    3122 og 3124 slåes sammen
    3173 Her går vi ut frå at det vert eit mindre kull

******** Avdeling 5200 Korarbeid

******** Avdeling 5555 Barne- og ungdomsarbeid
    3272 Eventuell foredragsholder SøndagskveldpåLandås
    3206 Høgtalar frå Gaute
    3151 Herunder LIV-kurs?
    3173 Nattcup og anna (minus eigenandel)

******** 6500 Diakoni
   Som i år.

   Generelt: samla underskot 45000 (dvs. ta frå bankkontoen)
   Skåret ned på ein del aktivitetar som vi ikkje har gjort noko med i år.

   Auke givertenesta



**** Møteplan for våren


**** Julegåver i samarbeid med diakonen i Slettebakken [Seier vi ja til fem gåver?]
Inviterer diakonen i Slettebakken til eit menighetsrådsmøte i 


**** Vurdering av halvåret


**** Rullere årshjulet


** 2019

*** Januar
17. januar
Saksliste
1. Godkjenning av innkalling
2. Godkjenning av referat/møtebok desember 2018
   1. Kapellan utlyst (saman med mange andre) med frist 10. februar. Tilsetjing i bispedømmet 20. mars.
3. Nominasjonskomite for valet 2019 (treng tre medlem)
   1. Odd Helge Gilja (har vore før)
   2. Svein Davidsen (har vore før)
   3. Ragnar Tvinnereim (har vore før)
   4. Jan Frode Sandvik
   5. Ingrid Drange
   6. Heidi Westli 
   7. Åse Åtland
4. Samarbeid med Fridalen om adm. leiar. (Berit: om  samarbeide på to stillingar)
   1. Aasmund snakker med leiar i Fridalen fredag. Staben i Landås er delt; Hilde er mest skeptisk. Soknerådet spør om det er greitt å "dele seg" mellom to menigheter. Dersom adm. leiar vert redusert til 50 % bør desse 10 % overførast til frivilligehtskoordinator (slik at denne vert 40 %). Arbeidsdeling mellom desse to stillingane må ryddast i. Delt stilling medfører meir kveldsarbeid og kanskje mindre fysisk tilstades på dagtid. Men dette tvinger seg nok fram, og vi må få til dei beste ordningane. Kanskje skal vi tenke om kven som skal vere dagleg leiar i menigheten!
5. Åpen barnehage om uteplass (vedtak: vi er positive)
   1. Vi er positive, og kan starte arbeidet med å utforme skisse saman med BKF. Ønskeleg å spørre arkitekten som teikna Landås skole, Børje Sundt Låstad, Aina spør. 
6. Offerliste
7. Menighetsbladet (kan vi kombinere redaksjonsvervet med nettsidene)
   1. Bladet har hittil ikkje fungert som kommunikasjonskanal. Trist å miste bladet. Det gode stoffet i bladet er intervju/reportasjer. Kanskje bladet skal brukast til *presentasjon* av menigheten, ikkje *informasjon*. Kan vi få ein betre informasjonsflyt gjennom nettsidene? Redaksjonen kjenner seg sårbare, for det har vore mykje arbeid. Dei har kjent seg "på hæla". Komiteen kan gjerne sitje, men vi treng ein redaktør. Torbjørn? Vi treng ein i staben som kan ta seg av informasjonskanalen på nettet. Redaksjonen lager to flotte blad, og staben/frivillige tar seg av nettsidene. Den siste bør vere ein som har teknisk kompetanse, men også ein eigen drivkraft til å skaffe stoff frå stab/frivillige. Etter at Gaute har snakka med redaksjonen kan soknerådet gå breitt ut og finne ny redaktør. Kan vi tenkje oss Lars Ove Kvalbein som redaktør? Kunne vi tenkt ein "redaksjon" som også skriv til nettet? Men
   2. Jørgen Thomassen (kanskje han har andre namn), Nikolai Vinnes Seip (?), Simen (?) 
8. Orienteringssaker
   1. LME v/Aina
      1. Bestille transport for dei eldre, "det bobler" i styret; styreleiar og dagleg leiar er veldig dyktige. Jorunn Johnsen (pensjonist frå Slettebakken) tar gudsteneste kvar veke.
   2. BKF v/Hilde
      1. Ikkje til stades
   3. Brev til BKF om administrasjonsleiar [kopi til arkiv.bergen@kirken.no]
      1. Har tatt opp under sak 4/2019
   4. Dåpsløftet
      1. Åse Kristin orienterer om heftet. Alle bør snakke varmt om dåp.
   5. Årsstatistikk
      1. Tallene lagt fram
   6. Stabssituasjon
      1. Har ikkje fått svar på brev frå
   7. Status dusj/vaskemaskin/ladestasjon
      1. Arne Tveit kan ikkje svare på dette, men har sagt at det er bestilt utgreiing av oppvarming av kyrkjerommet
   8. Årshjulet
      1. Utsatt
   9. Vurdering av hausten 2018
      1. Utsatt


*** Februar

Saksliste
1. Representantar til bispedømerådet (e-post 21.12 frå Jens Meyer)
2. Revurdering av tomtegrensene:
   - Dersom vi ønsker å beholde tomta slik den er i dag (og det er heilt greitt for kommunen) så overtar vi (BKF) også *ansvaret* for vedlikehald (og ikkje minst strøing, sjå BA 24.01.2019). Så vi må tenke over konsekvensane av det vi gjer. Eg kjem til å foreslå at vi endrer tomtegrensene til det som Arne Tveit skisserer.
3. Oppstart av varmevurdering - skal vi ta stilling til det? Det er eit spark bak for igjen å sei noko om benker. Kva betyr "Vi må være sikre på at den løsningen som til slutt velges, kan kobles mot «Medarbeideren»"?
4. Årsmelding 2018 - vi må starte innsamling av meldingar frå undereiningane.
5. Høyring om samarbeid / arbeidsdeling (som hadde frist 1. februar)



1. Utlysingstekst for adm.leiar (vedlagt). Eg foreslår at det vi kjem fram til går til dei andre i soknerådet på e-post, og at vi leverer svaret fredag morgon. Altså ikkje sak til soknerådet. [Dersom Berit har svart på mitt innspel kan dette bli referert i rådsmøtet]
2. Årsmelding 2018. Årsmeldinga for 2017 er vedlagt; vi må finne ut kven som skal bli utfordra på å skrive korte meldingar. Denne kan vi ta med til soknerådet for ei (kort) drøfting om innhaldet. [Tar opp som sak]
3. Høyring om samarbeid/arbeidsdeling (vedlagt). Denne hadde frist 1. februar, og eg hadde fullstendig gløymt den ut. Men vi har jo drøfta dette inndirekte (indirekte?) i samband med adm. leiar-stillinga, så eg tenkjer at vi skal klare å lage eit kort skriv som kan gå på rundgang per e-post og så bli sendt i løpet av helga. Den treng heller ikkje vere på soknerådet. [Landås vil, men Fridalen vil ikkje]
4. Oppstart av varmeutredning (vedlagt). Skal vi drøfte dette i soknerådet? Det er jo eit "spark bak" for å få oss til å setje i gang diskusjonen om å skifte ut plast-reserveløysingane? [Tar opp som sak]
5. Revurdering av tomtegrensene: i samband med saken i BA 24. januar (vedlagt) har eg diskutert dette med kirkebyggsjefen, og han er tydeleg på at dersom Landås vil ha den tomta vi har i dag så får vi (altså BKF) ansvaret for strøing. Kva skal vi meine her? Kirkebyggsjefen og eg meiner at dersom vi beholder det gule området i skissen (vedlagt) så er det kommunen som overtar gangvegane. [Foreslår at A, B og C vert solgt til kommunen.]
6. Husstyret: vi må få dette opp att. Vi treng to gode namn. [Svein Davidsen er med]
7. Påsken 2019: Åse Kristin orienterer.
8. Eventuelt


Administrasjonsleder:
Det må vere eit krav at løna er administrasjonsleiar i heile stillinga.


*** Mars
4. mars: ekstraordinært møte for å nominere til kapellan

Saksliste:

 * Utsatt sak om eigedom. Aasmund snakker med Arne Tveit om deling av gangveg (ideell halvpart?) og konsekvensar for BKF.
 * Varme: Åse Kristin undersøker om vi kan få benker
 * Orientering frå Fellesrådet
 * Orientering frå LME
 * Eventuelt


**** Innstilling
Landås menighetsråd har i møte 4. mars diskutert søkerne til kapellanstilling og vil komme med følgemde uttalelse:

Vi har to gode søkere. Begge vil, etter menighetsrådets mening, kunne fungere bra i stillingen, og det var vanskelig å velge. Etter avstemning valgte vi å innstille Kristin Hjertaker på første plass, og Kjetil Austad Endal på andre plass. Det avgjørende var at Kristin har uttrykt et ønske om å bli værende i stillingen, og dette vil skape en stabil stabssituasjon på sikt.

Avstemmingen ga dette resultatet:
Kristin Hjertaker: 6 stemmer
Kjetil Austad Endal: 1 stemme
1 stemte blankt

Til stede: Hilde Trætteberg Serkland, Aasmund Kvamme, Helga Bjørnøy Urke, Hilde Eldevik Rusaas, Aina Langørgen, Bjørg Torkildsen Møllerløkken, Åse Kristin Nøkling Aagaard, Mette Waaler.   


*** April
*Husstyret*: Svein Davidsen og AU utarbeider mandat for husstyret, ny vårdugnad før konfirmasjonen 2. mai

*Grunnbok*: Vi /bør/ gi frå oss alt; det gir BKF betre handlingsrom for anna vedlikehald/nybygg

*Årsmøtet*: Planar? Jon lager oversikt over kven som har sendt, og Aasmund purrer

*Intervju*: fredag 5. april, Åse Kristin deltar

*Givertjeneste*: vi deltar på kurs om givertenesta i regi av BKF

*Konfirmasjonsgudstenester*: 5-årsplan

*Større variasjon i offer*: Fleire å spele på blant dei eksterne; alle vert bedt om å komme med sine ønsker.

*Fornying av avtaler*: Jon/Melanie ser på generell leieavtale for slike som Erik (med inntekt) og Håvard (utan inntekt).

*Økonomirapport*: 



*** Mai
Saksliste sendt til Jon i løpet av tysdag kveld.


*** Juni

**** Til AU, 4. juni
- Overgang for Jon/Svein og Jo
- Møteplan hausten: Vi må ha møter i august, september (etter valet), oktober (førebu budsjett) og november (overgang til nytt råd). NB! Det gamle rådet går av 31. oktober, og det nye går på 1. november. Eg foreslår at vi legg eit møte tidleg i november der det gamle rådet ønskjer det nye velkommen, og så går sin veg. Det nye rådet får eit framlegg til budsjett for 2020.
- Om valet: materiell, presentasjon av kandidatane, manntal, førehandsrøysting, ... (side 70++ i [[https://www.dropbox.com/s/98z8bafsr2od2by/valghandbok_kirkevalget2019.pdf?dl=0][dette heftet]]).


*** August

**** Velkomst for Kjetil sundag 1. september
- Kyrkjekaffe ved soknerådet

**** Avvikling av soknerådsvalet
- Trykke stemmesetlar
- Frivillige på valdagen
- Oppteljing
- Anna materiell (urner, ...)

**** Innspel til budsjett 2020
Sjå e-post frå Jon Funder Nævdal 20. mai 2019, og [[https://www.dropbox.com/s/rrt4qx4zizky4aj/Innspill%20til%20budsjett%202020%20og%20%C3%B8konomiplan%202021%20-%202024.docx?dl=0][dette dokumentet]]. Frist er *10. september*


*** September

**** Valet

**** Starte budsjettarbeid


*** Oktober


*** November

**** Felles med det nye rådet
Korleis gjer vi dette?


** FERDIG Giverteneste <2019-05-10 fre.>
 Melding om kven som er giverteneste-koordinator
** FERDIG Uteplass <2019-05-13 man.>
 Lag skisse til Arne Tveit og be om utredning 
** FERDIG Attestere faktura <2019-05-24 fr.>
